### ISSUE TITLE
Installation error pac4j

### ISSUE THREAD

**Issue by shnatyk** [alvarosanchez/grails-spring-security-rest#14]
I am having problem with plugin install...

I put "compile..." command in BuildConfig then refresh dependecies and got this message: 
"| Error Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information): - org.pac4j:pac4j-oauth:1.5.0-SNAPSHOT"

**Comment by ppazos** [comment]
I'm having the same issue in Grails 2.4.4 and:

compile ":spring-security-core:2.0-RC5"
compile ':spring-security-rest:1.5.2', {
   excludes: 'spring-security-core'
}

**Comment by towijo** [comment]
This example does not work with spring-security-rest 1.5 (and probably not 1.4). They changed in 1.4 how the plugin was overriding "stateful" Spring Security core beans. I just tried with 1.5 and got the regular spring security username/password login (stateful). When downgrading to spring-security-rest-1.3.3 it worked flawless with stateless/rest login. So i guess the example needs to be updated if its still alive.

**Comment by biniama** [comment]
I am getting this error:
`/Users/username/git-test/grails-spring-security-rest-sample/target/work/plugins/spring-security-rest-1.3.3/grails-app/controllers/com/odobo/grails/plugin/springsecurity/rest/OauthController.groovy: -1: Repetitive method name/signature for method 'java.lang.Object withFormat(groovy.lang.Closure)' in class 'com.odobo.grails.plugin.springsecurity.rest.OauthController'.
 @ line -1, column -1.
`
