### ISSUE TITLE
Authentication failed: Dynamic method get<Artefact>Class(artefactName) requires a single String parameter

### ISSUE THREAD

**Issue by Inlustra** [alvarosanchez/grails-spring-security-rest#144]
Unfortunately, when using the default DaoAuthenticationProvider, I'm met with the issue stated in the title. Forgive me if I'm wrong but I believe this is due to an invalid method call?
I have documented the issue in the following StackOverfow thread: 
https://stackoverflow.com/questions/26976390/grails-spring-security-rest-authentication-denied-dynamic-method-getartefactc

I'd be happy to provide any extra details you may require

**Comment by emfanitek** [comment]
Can't find the article on SO. Can someone at leaste leave a link?
