### ISSUE TITLE
Make plugin compatible with spring security core 1.2.7.3

### ISSUE THREAD

**Issue by manuelvio** [alvarosanchez/grails-spring-security-rest#15]
I'd like to try the rest plugin in my applications but they all depend on spring security core 1.2.7.3. I pulled the source and I tried to build it agains the old library adjusting the imported classes, but I think there are other changes that need a deeper approach in order to make the plugin work, such as new classes defined in spring security 3.2.0.
As an example, see SimpleGrantedAuthority class imported in OauthService.groovy.
I'm not a Spring security expert, so I apologize in advance if the task was trivial and I couldn't do it by myself.

**Comment by aonic** [comment]
+1

**Comment by antonevane** [comment]
@alvarosanchez  This issue can be closed.
