### ISSUE TITLE
Issue in redirecting to error page on slow internet or network failure

### ISSUE THREAD

**Issue by rajeev-oodles** [alvarosanchez/grails-spring-security-rest#156]
I am using spring security rest 1.4.0.RC5 for authentication with social networking sites. Whenever internet connection slow down MissingPropertyException exception is thrown  and 'No such property: code for class: org.scribe.exceptions.OAuthConnectionException' message is displayed.

Flow stops at url :
 "http://<my-app-url>/oauth/callback/facebook?code=AQByCirAO-5Uo9PIZ1J9Q9ilN1UAho8HIol56xp_4Z9Vm4EYNXWXd7NWPBInT5maBktP2Mq29JqzzRITllK2FudAsYwe1tIHmYR1USqCfLR7cYYrsK_htyGgqg9g7VxNHtEPlmcZ8PRcNczniTQh2CNz4y6bxdfqV9EVgczvin1xaOyENySRH2XPgl_kN9lx0c5CITPH1OXvYvHft_UFhAw3HUln-8udHLayEby1p18UVjujqTrJ4liBLdcUP7oe2dyMPn0WFhHuwe9dPG383gV8-pFaX8ujId1pHi5bCjYOyZL8KKWE9IwQJh3-yrNBVI8pElyajvKSdTz4XCBJbOBe&state=tKH84tplMh#_=_"

We are getting control on the callback controller but not able to render the gsp we need in case of these type of errors.

In case of success everything works fine but in case of any exception we are not able to make the flow complete for user (Who is using the social login) as we stuck on the above URL.

**Comment by alvarosanchez** [comment]
First of all, the version you use is odd. Please try `1.4.0`.

Secondly, I need the full exception output to see where is failing exactly.

Cheers.
