### ISSUE TITLE
Cannot resolve reference to bean 'eventPublisher' when useSecurityEventListener is true

### ISSUE THREAD

**Issue by erickmelo** [alvarosanchez/grails-spring-security-rest#157]
When this property of Spring Security Core is true: "grails.plugin.springsecurity.useSecurityEventListener = false", we face a missing bean referenced by 'restTokenValidationFilter'. Probably it's related to some change on bean name in the newest version of Grails (Grails 2.4.4)

```
Message: Error creating bean with name 'restTokenValidationFilter': Cannot resolve reference to bean 'eventPublisher' while setting bean property 'eventPublisher'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'eventPublisher' is defined
```

**Comment by erickmelo** [comment]
Duplicated ticket: #119

**Comment by alvarosanchez** [comment]
It's implemented but not released... yet. I will update this ticket when `1.4.1.RC3` is published.

**Comment by alvarosanchez** [comment]
Final release version was indeed `1.4.1`.
