### ISSUE TITLE
Modify 404 "Token not found" response

### ISSUE THREAD

**Issue by rblazquez** [alvarosanchez/grails-spring-security-rest#160]
I am implementing a custom TokenStorageService to both use redis and allow token expiration (not supported by Gorm).

I am throwing TokenNotFound exceptions in both loadUserByToken and removeToken when token not found (removed/is expired/...) and these exceptions gets translated to 404 and formatted by tomcat as usual tomcat html error responses.

Now ... i do not really get why a 404 instead of 401 responses are rendered ... and i cannot allow tomcat to take care of this since i am implementing REST api with JSON errors.

Is it possible to change the behavior? ... one thing, another or (better) both?

Thanks in advance,

**Comment by alvarosanchez** [comment]
You are probably missing a `ExceptionTranslationFilter` in your filter chain. Can you please verify that?

**Comment by rblazquez** [comment]
Sorry Alvaro,

I realized that the 404 status was a different problem.

Thanks for your help.
