### ISSUE TITLE
MissingMethodException from GormTokenStorageService

### ISSUE THREAD

**Issue by srekapalli** [alvarosanchez/grails-spring-security-rest#161]
Receiving exception when token not found.

Caused by: groovy.lang.MissingMethodException: No signature of method: java.lang.String.mask() is applicable for argument types: () values: []
Possible solutions: wait(), any(), wait(long), each(groovy.lang.Closure), is(java.lang.Object), take(int)
	at com.odobo.grails.plugin.springsecurity.rest.token.storage.GormTokenStorageService.loadUserByToken(GormTokenStorageService.groovy:32)

**Comment by alvarosanchez** [comment]
The `mask()` method is added by the plugin's `doWithDynamicMethods()`. Can you please `grails clean-all && grails compile`?

**Comment by srekapalli** [comment]
I have a unit test that expects TokenNotFoundException but I'm receiving MissingMethodException. Don't think String class got enhanced during grails unit test phase.

**Comment by alvarosanchez** [comment]
If you are in a unit test, I would suggest you to mock the method using the metaclass, for instance.

Anyway, the mask() method has been removed yesterday, so don't expect it to be in future releases.
