### ISSUE TITLE
The plugin doesn't generate AuthenticationSuccessEvent

### ISSUE THREAD

**Issue by sergsoft** [alvarosanchez/grails-spring-security-rest#162]
The plugin doesn't generate AuthenticationSuccessEvent.
I can override the common handler RestAuthenticationFailureHandler and add my handler like AuthenticationSuccessEvent, but it isn't a convenient way.

**Comment by alvarosanchez** [comment]
It indeed does, see #164 

You have to make sure you have enabled event publishing on Spring Security Core: http://grails-plugins.github.io/grails-spring-security-core/guide/events.html

**Comment by alvarosanchez** [comment]
By the way, make sure you have at least `1.4.1` version of my plugin.
