### ISSUE TITLE
Best Way to Return Token after Registration

### ISSUE THREAD

**Issue by aonic** [alvarosanchez/grails-spring-security-rest#163]
Hello

I am using this plugin for login/logout but also need to create an API endpoint for Sign Up.

What is the least hacky way to return a authorization token? I am using the Gorm token storage, so I could just make a new Token record and save/return it, but wanted to see if there is a way to "hook" into the existing filters to make this clean

**Comment by v1p** [comment]
try to chain the login method with registration i.e.
```
def register(){
...
def username = params.username
def password = params.password

chain(uri: "/api/v1/login", params: [username: username, password: password])
}
```

you might have to play around a bit to get it working, especially sending the params, as there's no way to pass on the 'request' as such in chain method.

Another way is if you can call the /api/v1/login with groovy-wslite RestClient (more of a hack though, but still quite a neat way) ... pass on the username & password to the url & respond with the result.

**Comment by v1p** [comment]
UPDATE:

There's this way too, but use it with caution i.e. never expose this method to any api whatsoever, keep it for internal use only!

```groovy
try{
                def userDetails = userDetailsService.loadUserByUsername(email)
                AuthenticationToken authenticationToken
                if(userDetails){
                    authenticationToken = new AuthenticationToken(
                            username: userDetails.username,
                            tokenValue: tokenGenerator.generateToken()
                    ).save()
                }
                def authenticationResult = new RestAuthenticationToken(
                        userDetails,
                        userDetails.password,
                        userDetails.authorities,
                        authenticationToken.tokenValue
                )

                SecurityContextHolder.context.setAuthentication(authenticationResult)

                return authenticationResult
        }catch(Exception ex){
            log.error ex.getMessage()
        }

```

**Comment by aonic** [comment]
Thanks!

I ended up adding a custom filter to do it with /api/v1/signup
