### ISSUE TITLE
bug in line 67 of RestOauthService 

### ISSUE THREAD

**Issue by mariosanroman** [alvarosanchez/grails-spring-security-rest#167]
Hi everyone! Sorry to bother you but...
Is there a bug in RestOauthService in line 67? String tokenValue = tokenGenerator.generateToken()
Should it be String tokenValue = tokenGenerator.generateToken(userDetails)?

Method generateToken in TokenGenerator is String generateToken(Object principal)

Thanks in advance

**Comment by alvarosanchez** [comment]
You are totally right, thank you very much for pointing it out. I will create a test for that scenario.

**Comment by mariosanroman** [comment]
You are welcome
Glad to help!

**Comment by alvarosanchez** [comment]
Let me keep this open until I fix it :)

**Comment by mariosanroman** [comment]
Sorry. I closed it by accident.

**Comment by alvarosanchez** [comment]
Fixed.
