### ISSUE TITLE
Access denied after successful token validation

### ISSUE THREAD

**Issue by nseara** [alvarosanchez/grails-spring-security-rest#168]
Hi all,
I have a Grails project which is mainly a REST API. The endpoints I defined work fine without spring security, and all urls are reachable and responding ok. So, moving to authentication, I installed the grails-spring-security-rest plugin, login works fine and give me a token but after the Principal is validated ok I am getting a 
"intercept.FilterSecurityInterceptor  - Secure object: FilterInvocation: URL: /api/v1/shipments; Attributes: [_DENY_] "

More detail at http://stackoverflow.com/questions/28422025/grails-spring-security-rest-plugin-and-pesimistic-lockdown

Thanks very much in advance

**Comment by alvarosanchez** [comment]
I answered you on SO. Closing this as is not an issue of this plugin
