### ISSUE TITLE
JVM crash in restful controller

### ISSUE THREAD

**Issue by ericbai** [alvarosanchez/grails-spring-security-rest#173]
Hi! 

Every time I try to do a database write in a restful controller, for example in the update action, my Grails app (version 2.4.4) runs fine until the line with the save call. Then, as soon as the save call is made, I get the following exception 

```
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at ../../../src/share/instrument/JPLISAgent.c line: 844
```

My controllers are annotated with @Transactional(readOnly=true) and any methods in my controller that require a database write are annotated with @Transactional. The JVM crash is solved when if I wrap the line with the save call in a withNewSession block. 

Any thoughts on what might be causing this? Could it have something to do with the filtering scheme? I have anonymous access enabled and have configured my filters exactly as described in the documentation. 

Thank you!
Eric

**Comment by alvarosanchez** [comment]
@ericbai does removing this plugin entirely from the app, solve the problem?
