### ISSUE TITLE
Question: How to update token expiration?

### ISSUE THREAD

**Issue by caseyscarborough** [alvarosanchez/grails-spring-security-rest#174]
I have a Grails app using AngularJS as the front-end. Everything works perfectly, except that if a user is using the app when their token expires, it denies them access to the API forces a re-login. I'm using the exact setup specified in this image from the documentation, except using JWT (not storing the token).

![](http://alvarosanchez.github.io/grails-spring-security-rest/docs/img/rest.png)

What is the best way to avoid this? Should I be updating the client's token in some way periodically?

**Comment by alvarosanchez** [comment]
@caseyscarborough as per OAuth 2 specification (which is why the JWT implementation follows), the token expiration does not change. So once it expires, your chances are:

1. Your front-end requests a new token by restarting the authentication flow.
2. If the above is a problem in terms of user experience, then you should use refresh tokens. Refresh tokens never expire (or have a very long expiry time), and allow you to get new access tokens transparently to the user.

Refresh tokens are not currently supported, but will be as part of the final 1.5 release of this plugin.

**Comment by caseyscarborough** [comment]
It looks like the refresh tokens are exactly what I'm looking for. Thank you for the help!

**Comment by robertoschwald** [comment]
Wondering why this ticket is already closed. 1.5 is not released and I didn't find anything about refresh tokens in the current 1.5 RC1 docs.

**Comment by alvarosanchez** [comment]
@robertoschwald agreed. I have to do a little more work to support and document refresh tokens. 

1.5.0.RC1 should have included that, so I'll re-release it and will keep this open meanwhile.

Sorry for the confusion.

**Comment by robertoschwald** [comment]
Great! Thanks!

**Comment by alvarosanchez** [comment]
@robertoschwald 1.5.0.RC2 has been published.

**Comment by mautematico** [comment]
@alvarosanchez could you please point us to TFM about refresh_tokens?
Your post does not cover that topic :(
http://alvarosanchez.github.io/grails-angularjs-springsecurity-workshop/

If I make a POST request like this one:
```
    if (jwtHelper.isTokenExpired(ariaAccessJWT)) {
      // A promise of a JWT id_token
      return $http({
        url: 'http://localhost:8080/oauth/access_token',
        skipAuthorization: true,
        method: 'POST',
        data: {
            grant_type: 'refresh_token',
            refresh_token: ariaRefreshJWT
        }
      }).then(function(response) {
        var ariaAccessJWT = response.data.access_token;
        localStorage.setItem('ARIA_access_jwt', ariaAccessJWT);
        return ariaAccessJWT;
      });
    } 
```
I get a response like this one:
```
{"timestamp":1468359720199,"status":401,"error":"Unauthorized","message":"No message available","path":"/oauth/access_token"}
```

May be am I using a wrong path or method? May be am I missing some URL param?
I'll be more than happy to send a PR to include this on the docs and TFM 💃 

¡Gracias!

**Comment by mautematico** [comment]
I am now using this applycation.groovy, and everything seems to work now as expected. :)

```
// Added by the Spring Security Core plugin:
grails.plugin.springsecurity.userLookup.userDomainClassName = 'com.example.User'
grails.plugin.springsecurity.userLookup.authorityJoinClassName = 'com.example.UserRole'
grails.plugin.springsecurity.authority.className = 'com.example.Role'
grails.plugin.springsecurity.controllerAnnotations.staticRules = [
        [pattern: '/', access: ['permitAll']],
        [pattern: '/error', access: ['permitAll']],
        [pattern: '/index', access: ['permitAll']],
        [pattern: '/index.gsp', access: ['permitAll']],
        [pattern: '/shutdown', access: ['permitAll']],
]

grails.plugin.springsecurity.filterChain.chainMap = [
        [
                pattern: '/api/**',
                filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'
        ],
        [

                pattern: '/**',
                filters: 'JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter'
        ]
]
```
