### ISSUE TITLE
Using Facebook OAuth fails

### ISSUE THREAD

**Issue by liftyourgame** [alvarosanchez/grails-spring-security-rest#178]
RestOAuthServer.storeAuthentication
calls tokenGenerator.generateToken() without passing the principal.
The principal is later need in: SignedJwtTokenGenerator
This results in the exception in AbstractJwtTokenGenerator.generateClaims()
Principal is null so the line: claimsSet.setSubject(principal.username) gives an error: Cannot get property username on null object.

Shouldn't the principal be created and passed in somewhere?

**Comment by taelerch** [comment]
if you change line 76
tokenGenerator.generateToken(userDetail)

That got me going.

**Comment by alvarosanchez** [comment]
What you pointed out it's already resolved in the upcoming version branch, `release/1.5.0`.

Thanks for the feedback anyway, and stay tuned for the next milestone!
