### ISSUE TITLE
I am not capable of installing the latest version of the plugin

### ISSUE THREAD

**Issue by ababira** [alvarosanchez/grails-spring-security-rest#180]
I tried to install the plugin using the instructions here 

http://alvarosanchez.github.io/grails-spring-security-rest/

Here is the console output when i run an empty project 

|Loading Grails 2.4.4
|Configuring classpath
Error |
Resolve error obtaining dependencies: Could not find artifact org.grails.plugins:spring-security-rest:zip:1.5.0.M3 in repo_spring_io_milestone (http://repo.spring.io/milestone) (Use --stacktrace to see the full trace)
Error |
Resolve error obtaining dependencies: Could not find artifact org.grails.plugins:spring-security-rest:zip:1.5.0.M3 in repo_spring_io_milestone (http://repo.spring.io/milestone) (Use --stacktrace to see the full trace)
Error |
Could not find artifact org.grails.plugins:spring-security-rest:zip:1.5.0.M3 in repo_spring_io_milestone (http://repo.spring.io/milestone)
|Run 'grails dependency-report' for further information.

**Comment by domurtag** [comment]
I had the same problem with M3, but the previous milestone works

    repositories {
        inherits true // Whether to inherit repository definitions from plugins

        grailsPlugins()
        grailsHome()
        mavenLocal()
        grailsCentral()
        mavenCentral()

        mavenRepo 'http://repo.spring.io/milestone'
    }

    plugins {
        compile ":spring-security-core:2.0-RC3"
        compile ":spring-security-rest:1.5.0.M2", {
            excludes: 'spring-security-core'
        }
    }

Could someone confirm my assumption that  `:spring-security-core:2.0-RC3` is the correct version of the core plugin to use with `:spring-security-rest:1.5.0.M2`?

**Comment by alvarosanchez** [comment]
Too fast, guys :). 1.5.0.M3 is not published yet. The milestone is not flagged as closed: https://github.com/alvarosanchez/grails-spring-security-rest/milestones

Check that first to ensure what is the latest version. As the time of writing, it is 1.5.0.M2

**Comment by donalmurtagh** [comment]
The reason for the confusion is that [this page](http://alvarosanchez.github.io/grails-spring-security-rest/) indicates 1.5.0.M3 is the current version

**Comment by alvarosanchez** [comment]
Oops, that's right. The problem with that page is that it shows the latest build. But I'm planning to change that anyway before 1.5 GA.

Thanks for pointing it out!

**Comment by donalmurtagh** [comment]
No problem, BTW, can :spring-security-core:2.0-RC4 be used with M2 or is only :spring-security-core:2.0-RC3 the only supported version?

**Comment by alvarosanchez** [comment]
It can, and it's the version used internally. I will update that page too. Sorry for the confusion.
