### ISSUE TITLE
various improvements to docs

### ISSUE THREAD

**Issue by domurtag** [alvarosanchez/grails-spring-security-rest#183]
[Section 7](http://alvarosanchez.github.io/grails-spring-security-rest/docs/guide/tokenStorage.html) of the docs says

> The tokens are stored on the server using a tokenStorageService bean. The plugin comes with out-of-the-box support for JWT, Memcached, GORM and Grails Cache, but you can use your own strategy implementing the TokenStorageService interface. 

When read in isolation, this sounds like the token is always stored on the server, but the default strategy (JWT) doesn't store any state server-side.

**Comment by alvarosanchez** [comment]
Agreed. I will clarify it.

Thanks.

**Comment by domurtag** [comment]
Great, you might also correct the following on the same page in the "Encrypted JWT's" section

> If the claims contains sensible information....

It should be

> If the claims contains sensitive information....

**Comment by domurtag** [comment]
I think I found another problem. At the bottom of the [Token Validation FIlter page](http://alvarosanchez.github.io/grails-spring-security-rest/docs/guide/tokenValidation.html) it indicates that the default value for the validation endpoint header is given as `X-Auth-Token`.

However, based on my testing it seems the header actually defaults to 
````
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0MjI5OTU5MjIsInN1YiI6ImppbWkiLCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImlhdCI6MTQyMjk5MjMyMn0.rA7A2Gwt14LaYMpxNRtrCdO24RGrfHtZXY9fIjV8x8o
````

**Comment by alvarosanchez** [comment]
You are right, that is there for historical reasons. I will change it too.

**Comment by alvarosanchez** [comment]
You will be listed on the home page as contributor :).

If you see anything else, feel free to reopen this or open a new issue.

Thank you for your collaboration.

**Comment by domurtag** [comment]
> You will be listed on the home page as contributor :).

Fame at last, thanks!

> Thank you for your collaboration.

No problem, thanks for responding so quickly to the issues I opened
