### ISSUE TITLE
Login only possible if user has a certain role

### ISSUE THREAD

**Issue by langerc** [alvarosanchez/grails-spring-security-rest#186]
Is there a way to allow login only if a user has a specified role? i share a userdatabase between 2 projects and want one group with the role ROLE_BACKEND to be able to login everywhere, all other users should not be able to login to one of the 2 portals.

i played arround with staticrules and the filtermap but was not able to acomplish what i need.

any tips are welcome.

**Comment by alvarosanchez** [comment]
This is a question related to underlying Spring Security, not this plugin.

To do what you want to do, you'd nee to implement your own authentication provider: http://grails-plugins.github.io/grails-spring-security-core/guide/authenticationProviders.html
