### ISSUE TITLE
Custom actions on logout

### ISSUE THREAD

**Issue by pmajcher** [alvarosanchez/grails-spring-security-rest#187]
Hi all,

I wonder if there's a possibility to add some custom actions on logout. I was trying to use Grails' Filter mechanism, but it looks like it works only for controllers. What's more, filters are separated from controllers, so any transactional changes are impossible.
In my case, I'd like to delete some row from DB on logout. It would be great if I could delete this row in one transaction with deleting access_token.

Cheers,
Piotr.

**Comment by alvarosanchez** [comment]
What you need is called logout handlers: http://grails-plugins.github.io/grails-spring-security-core/guide/logoutHandlers.html
