### ISSUE TITLE
Missing 1.5.0 documentation

### ISSUE THREAD

**Issue by ababira** [alvarosanchez/grails-spring-security-rest#188]
Hi,
I cant seem to find the docs for 1.5.0 anymore. In my case im using jwt to do my auth and i am struggling to understand how to decode the token on the server side in order to get the username or id of the logged in user and query the db. I realize its a trivial question but im not sure where to find the answer

**Comment by alvarosanchez** [comment]
You are correct. The docs will be published on http://alvarosanchez.github.io/grails-spring-security-rest/ for the next version I plan to release this week.

In the meantime, you can clone this repo, switch to the `release/1.5.0` branch and run `./grailsw doc` to generate the documentation.

**Comment by ababira** [comment]
Thanks,
The reason i wrote this is that i remember that whenever i was checking the docs  a few weeks ago they were for v 1.5 and now they seem to have disappeared. But anyway i found what i was initially after so thanks again
