### ISSUE TITLE
upgrading from 1.5.0.M2 to 1.5.0.RC1

### ISSUE THREAD

**Issue by domurtag** [alvarosanchez/grails-spring-security-rest#189]
It seems that the package names have changed between these two versions. However, I'm unable to find the replacement for `com.odobo.grails.plugin.springsecurity.rest.RestAuthenticationToken`.

When using 1.5.0.M2 I would use `RestAuthenticationToken` in an action that saves a new user and logs them in

        UserDetails userDetails = userDetailsService.loadUserByUsername(user.username)
        String tokenValue = tokenGenerator.generateToken(userDetails)

        tokenStorageService.storeToken(tokenValue, userDetails)

        // I can't find a replacement for RestAuthenticationToken in 1.5.0.RC1
        Authentication authenticationResult = new RestAuthenticationToken(
                userDetails,
                userDetails.password,
                userDetails.authorities,
                tokenValue
        )
        SecurityContextHolder.context.authentication = authenticationResult

**Comment by alvarosanchez** [comment]
It has been refactored to https://github.com/alvarosanchez/grails-spring-security-rest/blob/release/1.5.0/src/groovy/grails/plugin/springsecurity/rest/token/AccessToken.groovy

**Comment by domurtag** [comment]
Thanks, I think the 1.5.0.RC1 equivalent of the code above is

    def signup(User user) {
        user = authService.register(user)

        UserDetails userDetails = userDetailsService.loadUserByUsername(user.username)

        AccessToken accessToken = tokenGenerator.generateAccessToken(userDetails)
        String tokenValue = accessToken.accessToken

        tokenStorageService.storeToken(tokenValue, userDetails)
        SecurityContextHolder.context.authentication = accessToken

        def tokenAsJSON = ['access_token': tokenValue] as JSON
        render contentType: 'application/json', text: tokenAsJSON, status: HttpStatus.SC_CREATED
    }

Although I think I can omit the `tokenStorageService.storeToken(tokenValue, userDetails)`. This code was ported from another project that stores tokens on the server-side, but in my case I'm using JWT, so I guess `tokenStorageService.storeToken` is a noop?

**Comment by alvarosanchez** [comment]
It is for JWT: https://github.com/alvarosanchez/grails-spring-security-rest/blob/release/1.5.0/src/groovy/grails/plugin/springsecurity/rest/token/storage/jwt/JwtTokenStorageService.groovy#L87

Anyway, 1.5.0.RC1 is incomplete and I'll have to rerelease it. See #174 for the reasons.

**Comment by domurtag** [comment]
Thanks for the heads-up about the refresh tokens. Can I suggest that when this dev has finished you release it as RC2 rather than re-releasing RC1? If you release it as RC2 then it'll be much more obvious when this functionality is available.

**Comment by alvarosanchez** [comment]
I thought on doing that. However, by re-releasing I wanted to emphasize that upcoming versions will be feature stable. By releasing as RC2, there will be feature additions from RC1, whereas only bug fixes should take place.

On the other hand, there is also the issue you mentioned, so I will probably do what you said and release a RC2 :)

**Comment by domurtag** [comment]
I'm not currently using refresh tokens, but I expect I will once they become available, so I'll check back regularly. I guess we can close this issue

**Comment by alvarosanchez** [comment]
@domurtag 1.5.0.RC2 has been published.

**Comment by donalmurtagh** [comment]
Thanks for the notification, I'll update right now

**Comment by domurtag** [comment]
Thanks for the notification, I'll update right now
