### ISSUE TITLE
springSecurityService.principal + JWT

### ISSUE THREAD

**Issue by andresarslanian** [alvarosanchez/grails-spring-security-rest#192]
Hello Alvaro, 
I've upgraded to 1.5.0.RC2 to use the refresh tokens. That's why I stopped using  GORM storage to start using JWT to support it.

The problem is that it stopped working the access to springSecurityService.principal.id receiving:
No such property: id for class: org.springframework.security.core.userdetails.User.

So if I use GORM it works, if I use JWT it doesn't. 

Any suggestion?

Thank you very much for your help!

**Comment by alvarosanchez** [comment]
Good catch. I have decided now to serialize the principal received into a String, so whatever object given by the authentication provider (`DaoAuthenticationProvider` in your case) will be restored later.

Will be ready on `1.5.0.RC3` once the build completes.

**Comment by andresarslanian** [comment]
thanks!!!!
