### ISSUE TITLE
document OAuth callback URL

### ISSUE THREAD

**Issue by domurtag** [alvarosanchez/grails-spring-security-rest#194]
Step 6 of the [OAuth sequence diagram](http://alvarosanchez.github.io/grails-spring-security-rest/1.5.0.RC3/docs/guide/oauth.html) shows the OAuth provider redirecting to a "Grails callback URL", but I don't think this URL is documented anywhere

The general format of this URL is `${grails.serverURL}/oauth/callback/${providerName}`. It's important that a user of the plugin is aware of this, because most/all OAuth providers require you to configure this URL within your application settings.

**Comment by alvarosanchez** [comment]
Good catch, I'll do it.
