### ISSUE TITLE
JWT test app could not find artifact org.grails.plugins:spring-security-rest:zip

### ISSUE THREAD

**Issue by ggomez1973** [alvarosanchez/grails-spring-security-rest#195]
I've clone the repo, move to the test apps, jwt. Did grails run-app and i get Could not find artifact org.grails.plugins:spring-security-rest:zip:1.5.0-SNAPSHOT in grailsCentral. I'm using the same version describe in the properties 2.4.4

**Comment by alvarosanchez** [comment]
You have to switch to the `release/1.5.0` branch.
