### ISSUE TITLE
1.5.0.RC4 changes - JWT

### ISSUE THREAD

**Issue by andresarslanian** [alvarosanchez/grails-spring-security-rest#199]
Hello Alvaro,

I have doubts on the changes introduced on the new release.

With the version 1.5.0.RC3, when I tried to log POSTing to ```/api/login``` using JWT, everything seems to work, receiving the token without any problem.

The problem with 1.5.0.RC3 is that then when I try to access any of the methods of ```api/***``` sending for example:

In the header:
``` 'Content-Type': 'application/x-www-form-urlencoded' ```

and then in the POST data:
```access_token: TOKEN, param1: paramValue ... ```

I receive a 500 error (problem in the server).

But, without changing anything, when I've updated to 1.5.0.RC4, this last step works correctly, returning the desired results BUT it stopped working the call to ```/api/login``` since I've started receiving a 500 error when I invoke that login method.

The client code is exactly the same with the version of 1.5.0.RC3 and 1.5.0.RC4. In the first case I receive an error when calling any method (except for login that I receive the token) and in the second case everything works except the call to login.

It's hard to send you the output of the DEBUG because if I test locally in my machine I receive the ```Servlet.service() for servlet [default] in context``` error, so all this I'm trying it in a remote server that this issue is not present.

Please let me know if I can help in some way.

Thanks!

**Comment by alvarosanchez** [comment]
I need full debug output, and full request details, of the RC4 case, please.
