### ISSUE TITLE
/oauth endpoint

### ISSUE THREAD

**Issue by andresarslanian** [alvarosanchez/grails-spring-security-rest#200]
Hello Alvaro,

Is it possible to evaluate the possibility of changing the endpoint ```name oauth: "/oauth/${action}/${provider}"(controller: 'restOauth') ``` for the token refresh?

I know that it's not your concern, but the ```spring security oauth ``` plugin (http://grails.org/plugin/spring-security-oauth) uses the same endpoint. Since you are using the ```/api```path, you could put it there so all the methods are grouped in the same path... something like ```/api/oauth```

I don't know, it's just a suggestion.

Thanks!

**Comment by alvarosanchez** [comment]
If you are using both plugins, you can remap it if you want, as your `UrlMappings` will always take precedence over the plugin's:

```groovy
"/oauth/$provider/success"(controller: 'springSecurityOAuth', action: 'onSuccess')
"/oauth/$provider/failure"(controller: 'springSecurityOAuth', action: 'onFailure')
"/api/oauth/${action}/${provider}"(controller: 'restOauth')
```
