### ISSUE TITLE
expires_in time seems wrong in RC4

### ISSUE THREAD

**Issue by mattchanner** [alvarosanchez/grails-spring-security-rest#203]
I have upgraded to RC4 and noticed something odd.  The expires_in JSON attribute looks like it only returns the seconds part of the expiration date delta.

This is an example taken from the debug log when I log in:

2015-05-06 15:53:16,859 [http-bio-8080-exec-25] DEBUG rest.RestAuthenticationProvider  - Now is Wed May 06 15:53:16 BST 2015 and token expires at Wed May 06 16:42:36 BST 2015
2015-05-06 15:53:16,859 [http-bio-8080-exec-25] DEBUG rest.RestAuthenticationProvider  - Expiration: 19

The JSON then looks like this:

{
   "access_token": "token is here",
   "roles": [
      "ROLE_ADMIN",
      "ROLE_USER"
   ],
   "token_type": "Bearer",
   "expires_in": 19,
   "username": "username"
}

Is this a bug?

Thanks!

Matt

**Comment by alvarosanchez** [comment]
It is clearly a bug. Sadly, I have just released 1.5.0. I will have to release a 1.5.1 version :(

Thanks for reporting it. I will fix it ASAP.

**Comment by mattchanner** [comment]
Great thanks!

Interestingly, the oauth/access_token endpoint returns the correct value here.

**Comment by alvarosanchez** [comment]
Because that endpoint creates a new token, so the expiration time is the original value.

The one you mentioned first calculates the remaining expiration.

Once Travis finishes the build, 1.5.1 will be out there.

**Comment by mattchanner** [comment]
Works like a charm, thanks!
