### ISSUE TITLE
how to increase login/logout performance using plugin spring-security-rest:1.4.0.RC5

### ISSUE THREAD

**Issue by tdigambar** [alvarosanchez/grails-spring-security-rest#205]
hi i am using this plugin in my project- i am using grails 2.4.2 in my config.groovy i have set like-
```groovy
grails.plugin.springsecurity.rest.token.validation.useBearerToken = false
grails.plugin.springsecurity.rest.token.validation.headerName = 'X-Auth-Token'
grails.plugin.springsecurity.rest.token.storage.useGrailsCache=true
grails.plugin.springsecurity.rest.token.storage.grailsCacheName='message'
grails.plugin.springsecurity.rest.token.validation.enableAnonymousAccess=true
grails.plugin.springsecurity.rest.login.active= true
grails.plugin.springsecurity.rest.login.useJsonCredentials = false
grails.plugin.springsecurity.rest.login.useRequestParamsCredentials	= true
grails.plugin.springsecurity.rest.login.usernamePropertyName =	'j_username'
grails.plugin.springsecurity.rest.login.passwordPropertyName = 'j_password'
```
as i am using jmeter for 600 user

**Comment by alvarosanchez** [comment]
The version you are using is very odd, pick any of http://alvarosanchez.github.io/grails-spring-security-rest/

What is the specific problem do you have?

**Comment by tdigambar** [comment]
thanks for the reply,i have used latest version as u mention above
i do not have any problem with plugin its working fine but
i am trying to increase login performance

**Comment by alvarosanchez** [comment]
The performance of the login will be mostly affected by the actual authentication provider you use (DB, LDAP, etc). The login endpoint in the plugin is implemented as a Servlet filter with minimal overhead.
