### ISSUE TITLE
Support events during authentication that include the accessToken. Standard and OAuth.

### ISSUE THREAD

**Issue by Schlogen** [alvarosanchez/grails-spring-security-rest#206]
I have implemented the standard Spring Security events, but the issue is that they don't get triggered during normal authentication or OAuth authentication.

**Comment by Schlogen** [comment]
PR issue #207 submitted

**Comment by alvarosanchez** [comment]
Events are published on token validation: https://github.com/alvarosanchez/grails-spring-security-rest/blob/develop/src/groovy/grails/plugin/springsecurity/rest/RestTokenValidationFilter.groovy#L82

Would that suit you?

**Comment by Schlogen** [comment]
Unfortunately no. I need to know exactly when the tokens get created. That gets published every time the user hits an endpoint with a valid token. I have a new PR that will be coming tonight. 

I plan on extending the `DefaultAuthenticationEventPublisher` by creating a `RestAuthenticationEventPublisher` that will have a `publishTokenCreation` method. It will publish a new `RestTokenCreationEvent` that takes in the access token to make it available to the event handlers. I will publish the event in the `RestOauthService` and the `RestAuthenticationFilter` after the `tokenStorageService.storeToken` method is called.

 I will also register a `RestSecurityEventListener` for the event as well so users can specify the closure in the config like spring security core.

What do you think?

**Comment by alvarosanchez** [comment]
Why a call to `EventPublisher.publishAuthenticationSuccess(accessToken)` from `RestAuthenticationFilter`  wouldn't suffice?

**Comment by Schlogen** [comment]
Because the work that needs done can only happen on token creation. I think having the `publishTokenCreation` call `publishAuthenticationSuccess` wouldn't be a bad idea either.

**Comment by Schlogen** [comment]
@alvarosanchez Is this something you would accept? I don't want to spend time creating a PR if you don't want it at all. It will open up the door to register other events as needed.

**Comment by Schlogen** [comment]
@alvarosanchez I submitted a PR for this #208

**Comment by alvarosanchez** [comment]
Closing this in favour of #208
