### ISSUE TITLE
Move OAuth support into a separate plugin

### ISSUE THREAD

**Issue by domurtag** [alvarosanchez/grails-spring-security-rest#209]
The OAuth support in this plugin is great, but obviously is tied to the use of REST tokens. Would you consider moving this into a separate plugin (which would then become a dependency of the Spring Security REST plugin), so that this OAuth support could be used in "traditional" Grails apps?

**Comment by alvarosanchez** [comment]
Not sure if there is room for yet another OAuth consumer Grails plugin. I'll leave this on hold to see if there is more community interest.

**Comment by donalmurtagh** [comment]
IMO there's room for a good one :)

**Comment by ask10000** [comment]
+1 . Also please add a flow of how to intergrate OAuth for mobile app.

**Comment by ejaz-ahmed** [comment]
I don't think it should be moved out of this plugin as there is already one out there.
