### ISSUE TITLE
Integrate grails-spring-security-rest with spring security oauth provider2 plugin

### ISSUE THREAD

**Issue by ferasodh** [alvarosanchez/grails-spring-security-rest#211]
Hi,

I have a grails application which is using oauth provider2 plugin. I want to integrate social provider using spring security rest plugin is this possible for the 2 plugins to work together? what configuration do I need to change?

Thanks,
Feras

**Comment by alvarosanchez** [comment]
It is possible. I'm doing it in a corporate application we have at work.

This is the configuration I have on BuildConfig:

```groovy
compile ":spring-security-core:2.0-RC4"
compile ":spring-security-rest:1.5.1", {
    excludes 'spring-security-core', 'cors'
}
compile ":spring-security-oauth2-provider:1.0.5.2", {
    excludes 'spring-security-core'
}
```
