### ISSUE TITLE
Password reset functionality to plugin

### ISSUE THREAD

**Issue by Hi-Fi** [alvarosanchez/grails-spring-security-rest#213]
Is there any plans to include password reset functionality to plugin? Grails-spring-security-ui seemed to contain it, so it would be good addition to this, too.

**Comment by alvarosanchez** [comment]
Password reset is totally dependant on which authentication provider you use to store your users: DB, LDAP, etc. And this plugin is provider agnostic.

There is an additional problem with password reset: which flow would you use? Simply a POST to an endpoint with the old and the new password? Or you send him an email with a link to set the new password?

There are many alternatives, and I see this feature as totally application-specific, so answering your question, there are not plans to add this to the plugin.
