### ISSUE TITLE
locked, disabled, expired, etc. accounts should not authenticate via OAuth

### ISSUE THREAD

**Issue by domurtag** [alvarosanchez/grails-spring-security-rest#214]
`OauthUserDetailsService` is responsible for providing information about a user that authenticates via OAuth to the spring security framework in the form of an `OauthUser`, which implements `UserDetails`

````groovy
interface OauthUserDetailsService extends UserDetailsService {

    OauthUser loadUserByUserProfile(CommonProfile userProfile, Collection<GrantedAuthority> defaultRoles) throws UsernameNotFoundException
}
````

In my application, `loadUserByUserProfile` returns an instance of the following class

````groovy
class LockableOauthUser extends OauthUser {

    private final boolean accountLocked

    LockableOauthUser(String username, String password, Collection<? extends GrantedAuthority> authorities, CommonProfile userProfile, boolean accountLocked) {
        super(username, password, authorities, userProfile)
        this.accountLocked = accountLocked
    }

    @Override
    boolean isAccountNonLocked() {
        !accountLocked
    }
}
````

which allows a user to be locked/unlocked. I was expecting authentication to fail is a user is locked, but this property is ignored. It seems this property should be checked, and authentication should fail if the account is locked. Similarly for these other properties of `UserDetails`:  `isAccountNonExpired()`, `isCredentialsNonExpired()`, `isEnabled()`.

The obvious place to add these checks is in the `storeAuthentication` method of `RestOauthService`. If any of these methods indicate that authentication should fail, an appropriate exception could be thrown, e.g. in the case of a locked account an instance of `org.springframework.security.authentication.LockedException`. This exception handler in `RestOauthController.callback` would need to be extended to return appropriate parameters to the client for each failure case (so that the client can figure out why authentication failed)

````groovy
        } catch (Exception e) {
            String errorParams

            if (e instanceof UsernameNotFoundException) {
                errorParams = "&error=403&message=${e.message?.encodeAsURL()?:''}"
            } else {
                errorParams = "&error=${e.cause?.code?:500}&message=${e.message?.encodeAsURL()?:''}"
            }

            if (session[CALLBACK_ATTR]) {
                frontendCallbackUrl += errorParams
                session[CALLBACK_ATTR] = null
            } else {
                frontendCallbackUrl = frontendCallbackUrl.call(errorParams)
            }
        } 
````
I think it would be preferable to use a textual error code for these failure cases, e.g. `error=ACCOUNT_LOCKED` because I don't think there will be an obvious HTTP status for all of them.

I'm not sure if the authentication failure handler should also be invoked?

````groovy
authenticationFailureHandler.onAuthenticationFailure(request, response, exception)
````

**Comment by alvarosanchez** [comment]
Well, this is an interesting request. There is already a place inside Spring Security Core where those checks are performed: `DefaultPostAuthenticationChecks`.

I can bring those checks into `DefaultOauthUserDetailsService`. Let me give it a try.

**Comment by donalmurtagh** [comment]
I had a quick look at the code changes and it's not immediately obvious how (on the client side) to detect a login failure due to a locked, disabled, etc. account. Assuming this is possible, could you add something to the docs explaining how? Thanks for addressing this!

**Comment by alvarosanchez** [comment]
It is already specified in http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/guide/oauth.html:

> In case of any OAuth authentication failure, the plugin will redirect back to the frontend application anyway, so it has a chance to render a proper error message and/or offer the user the option to try again. In that case, the token parameter will be empty, and both error and message params will be appended:

> http://your-frontend-app.com/auth-success.html?token=&error=403&message=User+with+email+jimmy%40gmail.com+now+allowed.+Only+%40example.com+accounts+are+allowed

**Comment by donalmurtagh** [comment]
Sorry, I should have been clearer. What I'm suggesting is that there should be a specific error code for each known login failure mode (and a default for the others). For example, if login fails due to a locked account return something like

    error=ACCOUNT_LOCKED&message=Account+is+locked

If login fails because the account does not exist, return something like

    error=ACCOUNT_NOT_FOUND&message=Account+not+found

If login fails because the account is disabled, return something like

    error=ACCOUNT_DISABLED&message=Account+disabled

......

If login fails for an unknown reason return something like

    error=LOGIN_FAILED&message=Something+went+wrong

If this is the approach you've taken, then the error codes for each failure mode should be added to the docs. In my particular case, it's important than I can detect in the front-end app why the login failed because (for example) I handle a failure due to a locked account very differently to other cases.

It seems in the docs that you're trying to map these failures to HTTP status codes. I don't see the advantage of this approach over textual codes such as those above?

**Comment by alvarosanchez** [comment]
`error` has always been an HTTP status code. Changing that will result in breaking other users' applications.

`message` will contain the reason, as thrown by https://github.com/grails-plugins/grails-spring-security-core/blob/master/src/java/grails/plugin/springsecurity/userdetails/DefaultPreAuthenticationChecks.java

You can use those to determine the cause of the rejection.

And if you still need further customisations, my suggestion is to subclass `RestOauthController` and override `def callback(String provider)` action.

**Comment by donalmurtagh** [comment]
> You can use those to determine the cause of the rejection.

I think this means you'd have to have some code like the following in the front-end app

````javascript
if (message == "User account is locked") {

} else if (message == "User is disabled") {

}
// etc.
````
Personally, I find this a bit unpleasant and brittle. Would it be possible to add an additional `&error_code` parameter to the URL, which could be checked on the client-side and wouldn't break backwards compatibility?
