### ISSUE TITLE
enabling oauth provider note

### ISSUE THREAD

**Issue by rhodebump** [alvarosanchez/grails-spring-security-rest#219]
I followed the guide found at:
http://alvarosanchez.github.io/grails-spring-security-rest/1.5.1/docs/guide/oauth.html#google

When I went to my URL, http://localhost:8080/cmm/oauth/authenticate/google, I was not directed to google, but to my own login page.

I had forgotten to add a rule for "/oauth"  adding the following to my configuration fixed it. 		 
'/oauth/**': ['permitAll']

Works now, but perhaps add to documentation?

**Comment by alvarosanchez** [comment]
It really depends on how you have defined your filter chain. Not always you need to define it, look at this example:

https://github.com/alvarosanchez/grails-spring-security-rest/blob/develop/test/apps/jwt/grails-app/conf/Config1.groovy

That test application has a test for Facebook that is doing a whole roundtrip:

https://github.com/alvarosanchez/grails-spring-security-rest/blob/develop/test/apps/jwt/test/functional/grails/plugin/springsecurity/rest/FacebookSpec.groovy
