### ISSUE TITLE
Custom serialization of Principal 

### ISSUE THREAD

**Issue by brp-oskar** [alvarosanchez/grails-spring-security-rest#221]
The principal object (UserDetails) in the token is Java serialized and GZIP:ed. I would like to serialized it only as json to be able to read it at the web client.

The methods serialize() and deserialize() of JwtService are static witch makes it difficult to override the serialization.

Would it be possible to extract those methods to a separate bean eg. JwtUserDetailSerializer that could easily be replaced in resource.groovy?

**Comment by alvarosanchez** [comment]
The principal is serialized to later be restored when an incoming request is received with a JWT. That serialized object needs to be there as it is now, and is not meant to be overridden.

If you need custom information for the client, all you need to do is to implement your own version of `AccessTokenJsonRenderer`. See http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/guide/tokenRendering.html for more information.
