### ISSUE TITLE
Db H2 console is not available 

### ISSUE THREAD

**Issue by Manas101** [alvarosanchez/grails-spring-security-rest#224]
Hi,
I use grails 2.4.4 and have installed the official grails spring-security-rest:1.5.1 plugin. After that we found out, that db console is not working, login form is shown but after login we get an error:

HTTP Status 500 - Unable to process parts as no multi-part configuration has been provided
java.lang.IllegalStateException: Unable to process parts as no multi-part configuration has been provided
	org.apache.catalina.connector.Request.parseParts(Request.java:2574)
	org.apache.catalina.connector.Request.getParts(Request.java:2542)
	org.apache.catalina.connector.RequestFacade.getParts(RequestFacade.java:1083)
	javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:345)
	javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:345)
	javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:345)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...

Is there any known solution or is it a bug?

Thanks a lot.

Jiri Sojka

**Comment by alvarosanchez** [comment]
The stacktrace you are posting is mostly useless to me, as no Spring Security class is on the stack.

Anyway, my suggestion is: make sure the stateless chain is *not* applied to your /dbconsole path. See http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/guide/configuration.html for more information.
