### ISSUE TITLE
Database token storage - get already existing token in database for a user

### ISSUE THREAD

**Issue by abozas** [alvarosanchez/grails-spring-security-rest#225]
Hi, 

For a business need, I needed to get already existing token from token table instead of overwriting existing as it is asked in other posts or generating new one. To have this specific behaviour, I modified RestAuthenticationFilter so as to get token value this way : 

            if (authenticationResult?.authenticated) {

                def conf = SpringSecurityUtils.securityConfig
                String tokenClassName = conf.rest.token.storage.gorm.tokenDomainClassName
                String tokenValuePropertyName = conf.rest.token.storage.gorm.tokenValuePropertyName
                String usernamePropertyName = conf.rest.token.storage.gorm.usernamePropertyName
                def dc = Class.forName(tokenClassName);

                def tokenObject = dc.findByUsername(authenticationResult.principal?.username);
                String tokenValue = tokenObject?."${tokenValuePropertyName}";
                if(!tokenObject) {
                    tokenValue = tokenGenerator.generateToken(authenticationResult.principal)
                    log.debug "Generated token: ${tokenValue}"

                    tokenStorageService.storeToken(tokenValue, authenticationResult.principal)
                } else {
                    log.debug "Token value found from the database: ${tokenValue}"
                }

                RestAuthenticationToken restAuthenticationToken = new RestAuthenticationToken(authenticationResult.principal, authenticationResult.credentials, authenticationResult.authorities, tokenValue)
                authenticationSuccessHandler.onAuthenticationSuccess(httpServletRequest, httpServletResponse, restAuthenticationToken)

I did this code in RestAuthenticationFilter.groovy but it seems too much specific for database token storage and I need to know : 
- Is that a good way to get existing token from a storage ?
- If it is possible to change interface TokenStorageService to have another method loadTokenByUser so as to get existing token for a specific user ?

Thanks in advance for your sharing,

Best regards,

Alexandre

**Comment by alvarosanchez** [comment]
Currently, the way you're doing it is the only way. Note that a reverse lookup by user would it be only possible in GORM, but not in the others, specially in JWT, so I'm not keen on changing the interface at this moment.

However, to keep your code cleaner, what I would do is: don't touch any filter at all, and simply provide your own `TokenGenerator`. Given your configuration, it would be `SecureRandomTokenGenerator`, so subclass it and override `AccessToken generateAccessToken(UserDetails principal)`. There you can use GORM to look for an existing token.
