### ISSUE TITLE
login with username or email ?

### ISSUE THREAD

**Issue by walshe** [alvarosanchez/grails-spring-security-rest#229]
I notice many sytems allow a user to login with a username or email together with a password.

Does the rest security plugin currently offer this ?

**Comment by alvarosanchez** [comment]
This plugin has nothing to do with where are your users or what do you have to do to authenticate them. All of that is performed by the Spring Security's `AuthenticationProvider`s you have configured. In a Grails application, it's GORM by default, or you can have others such as LDAP (`spring-security-ldap`).

See http://grails-plugins.github.io/grails-spring-security-core/guide/authenticationProviders.html for more information.

**Comment by walshe** [comment]
yeah thanks I figured it out, I just overrode loadUserByUsername() in my impl of GrailsUserDetailsService 

UserDetails loadUserByUsername(String nameOrEmail) throws UsernameNotFoundException {
		
			User user = User.findByNameOrEmail(nameOrEmail,nameOrEmail)
...
