### ISSUE TITLE
refresh_token invalidation issue

### ISSUE THREAD

**Issue by macchiatow** [alvarosanchez/grails-spring-security-rest#230]
If refresh_token stolen there is no way to prevent to login except by changing signature secret. jwt cannot be 100% stateless as needs to invalidate refresh_token after UserDatails change (such as password) in db

**Comment by alvarosanchez** [comment]
Refresh tokens are considered secret values, and it's your responsibility to protect it and keep it confidential. Also, as part of the OAuth 2.0 spec, it's mandatory to use SSL to all token transport operations.

Having said that, there are 2 solutions for your concern:
1) You can override `AbstractJwtTokenGenerator.generateRefreshToken` to set your preferred expiration.
2) You can implement your own token revocation mechanism by storing them wherever you want, and then overriding `RestOauthController.accessToken` with your own checks.
