### ISSUE TITLE
Tokens for users that dont exist anymore, get through authentication

### ISSUE THREAD

**Issue by machador** [alvarosanchez/grails-spring-security-rest#231]
I am using latest version of the plugin (1.5.2) and grails (2.5.1). 

The issue is that if a request comes to a Secured controller action with a token corresponding to a User that does not exist anymore, it gets validated anyway.

When checking on the controller the value in springSecurityService.currentUserId it contains the id of the user that does not exist anymore. 

Shouldn't the plugin check if the user still exists, and not just trust the token data?

How to reproduce:

1. Create a user
2. Get token in api/login with created user
3. Delete user
4. Access secured endpoint with token got in step 2.

**Comment by macchiatow** [comment]
After token issued it never checks database state. so you can delete user or change password access will still be granted

**Comment by machador** [comment]
But is this the desired token behaviour? Is it validated in the refresh token logic? Or a valid token + refresh token can't be invalidated?

**Comment by macchiatow** [comment]
auth token will invalidate when expires, refresh token will never invalidate as there is no expiration nor db check. You will have to implement your own JwtTokenStorageService that will check user db state

**Comment by machador** [comment]
Ok, thanks for your reply.

**Comment by alvarosanchez** [comment]
To add a little bit of insight about your question, the issue you are describing is also happening in the majority of applications using Spring Security (Grails or non-Grails).

With the traditional form-based authentication, once the user has authenticated, a `JSESSIONID` is generated and stored in a cookie. On every request the browser will send the cookie and the server will grant access if the session exists, no matter if the user has been deleted in the middle or not.

Note also that the plugin is flexible enough and you can replace almost every single piece with your own implementation. In this case, the part that decides if a token is valid or not is the `RestAuthenticationProvider`.

**Comment by machador** [comment]
Thanks @alvarosanchez for your comments. We actually solved it as you mention, and I understand the reasons for the decision.

**Comment by alvarosanchez** [comment]
:+1:
