### ISSUE TITLE
Revoking Token / Refresh Token

### ISSUE THREAD

**Issue by delfianto** [alvarosanchez/grails-spring-security-rest#232]
First of all, thank you for this great plugin.

I'm currently developing a restful web service for mobile client app (iOS/Android) so we're thinking about the possibility of user needing to revoke the access token and refresh token if for instance they lost their device. Is this kind of functionality is possible with the plugin (or even with JWT)?

**Comment by macchiatow** [comment]
no, I had to extend JwtTokenStorageService to verifyUserDetailsLastModified to invalide token after user record updated (for example after password change)

**Comment by alvarosanchez** [comment]
@delfianto please this comment: https://github.com/alvarosanchez/grails-spring-security-rest/issues/230#issuecomment-158380589
