### ISSUE TITLE
improve error handling in RestOauthController

### ISSUE THREAD

**Issue by domurtag** [alvarosanchez/grails-spring-security-rest#237]
As I mentioned in #234 I added a custom OAuth provider to my plugin configuration, which involved extending a bunch of Scribe classes. One of these base classes specifies timeouts for OAuth clients, and in my case the defaults were not sufficiently long. Before I extended these timeouts, the result was that a `org.pac4j.core.exception.TechnicalException` was being thrown from `org.pac4j.oauth.client.BaseOAuthClient:169` when I tried to login using this provider.

This exception was caught by the following exception handler in `RestOauthController`

````groovy
        try {
            // TechnicalException thrown here
            String tokenValue = restOauthService.storeAuthentication(provider, context)

            if (session[CALLBACK_ATTR]) {
                frontendCallbackUrl += tokenValue
                session[CALLBACK_ATTR] = null
            } else {
                frontendCallbackUrl = frontendCallbackUrl.call(tokenValue)
            }

        } catch (Exception e) {
            // TechnicalException caught here
            String errorParams

            if (e instanceof UsernameNotFoundException) {
                errorParams = "&error=403&message=${e.message?.encodeAsURL()?:''}"
            } else {
                // MissingPropertyException thrown here because the exception wrapped by 
                // TechnicalException does not have a code
                errorParams = "&error=${e.cause?.code?:500}&message=${e.message?.encodeAsURL()?:''}"
            }

            if (session[CALLBACK_ATTR]) {
                frontendCallbackUrl += errorParams
                session[CALLBACK_ATTR] = null
            } else {
                frontendCallbackUrl = frontendCallbackUrl.call(errorParams)
            }
        }
````

I've added some comments to the code to explain the flow. Ultimately, the problem is that 

    e.cause?.code

throws a `MissingPropertyException`, because the `org.scribe.exceptions.OAuthConnectionException` wrapped by `TechnicalException` does not have a `code` property.

Obviously it's fairly easy to prevent the `MissingPropertyException` by replacing:

````groovy
errorParams = "&error=${e.cause?.code?:500}&message=${e.message?.encodeAsURL()?:''}"
````
with something like:

````groovy
def errorParamValue = e.cause?.hasProperty('code') ? e.cause.code : 500
errorParams = "&error=${errorParamValue}&message=${e.message?.encodeAsURL()?:''}"
````

I mentioned this in #214, but in many cases the only way for the client to distinguish between different types of error, is by parsing the `message` which I dislike and suggested extending `errorParams` with an additional `error_code` parameter. A possible value for this parameter would be the simple class name of the exception or it's cause, e.g.

    errorParams += "&error_code=" + e.cause ? e.cause.class.simpleName : e.class.simpleName 

While this would be an improvement over the current approach it's still pretty inflexible. In order to provide complete control over how the exception is converted to a set of parameters (that are sent to the front-end app) a Spring bean that implements the interface below could be defined

````groovy
interface RestOauthErrorHandler {
  Map convert(Exception e)
}
````

and the error handling in the plugin would then be reduced to

````groovy
@Secured(['permitAll'])
class RestOauthController {

  RestOauthErrorHandler restOauthErrorHandler   

  def callback(String provider) {
 
    try {
      // impl omitted
    } catch (Exception ex) {
      Map errorParameterMap = restOauthErrorHandler.convert(ex)

      String errorParams

      restOauthErrorHandler.convert(ex).each { name, value ->
        errorParams += "&${name}=${value.encodeAsURL()}"
      }

      // the remainder of the code is unchanged
      if (session[CALLBACK_ATTR]) {
        frontendCallbackUrl += errorParams
        session[CALLBACK_ATTR] = null
      } else {
        frontendCallbackUrl = frontendCallbackUrl.call(errorParams)
      }
    }
  }
}
````

Naturally, the behaviour of the default implementation of this bean should be backwards compatibile with the current error handling.

If you agree with this proposal and would like me to submit a PR, let me know.

**Comment by alvarosanchez** [comment]
There are 2 things here:

1. Incorrect exception catching. It's clearly a bug. No doubts here.
2. Extending the response to include an error code. Maybe adding a new interface feels too much for me, but I agree that adding a new parameter to the response won't hurt.

I have been reading again RFC 6749 and maybe this is what we need:

```groovy
def errorParamValue = e.cause?.hasProperty('code') ? e.cause.code : 500
errorParams = "&error=${errorParamValue}&error_description=${e.message?.encodeAsURL()?:''}"
errorParams += "&error_code=" + e.cause ? e.cause.class.simpleName : e.class.simpleName 
```

Note that `message` has been renamed to `error_description`, as specified in the RFC. Also it is not forbidden by the spec to add new parameters.

What do you think about this?

**Comment by donalmurtagh** [comment]
Thanks for your response. I think the solution you propose is definitely an improvement on the error handling in 1.5.2, but I prefer the `RestOauthErrorHandler` approach I proposed.

The problem with your proposal is that it doesn't provide any easy way to return my custom data to the client when an error occurs. In my application, login will fail if user attempts to sign-in via OAuth with a locked account. In that case, I need to return the username of the account that attempted to login to the front-end. The only way to do this in 1.5.2 is with this horrible hack

    // this exception is thrown when a locked account is detected and will cause the username to be
    // returned at the value of the &error parameter
    throw new LockedAccountException(code: username)

The approach you've suggested means I will have to continue doing this, whereas with the `RestOauthErrorHandler` approach I have the flexibility to return whatever data I want to the front-end. 

You mentioned in your Twitter message that you'll be very busy over the next few weeks. If it helps, I could submit the code via a PR once we've agreed the approach?

**Comment by alvarosanchez** [comment]
Alright, you win :)

I'm happy with the `RestOauthErrorHandler` interface approach. Please cover it with tests and documentation.

For tests, you will need to:
1. Define a locked account in `BootStrap.groovy`: https://github.com/alvarosanchez/grails-spring-security-rest/blob/develop/test/apps/jwt/grails-app/conf/BootStrap.groovy
2. Add a new test inside `RestAuthenticationFilterSpec.groovy`. Note that the file exists 3 times in the project, one per testing app (one day I should refactor that, but for the time being, it is what it is).

If you have further doubts, we can continue the discussion in Gitter.

**Comment by donalmurtagh** [comment]
> Alright, you win :)

awesome, you won't regret this (don't quote me on that)

> Please cover it with tests and documentation.

of course

> For tests, you will need to:
> 1. Define a locked account in `BootStrap.groovy`:

I don't think I necessarily do need to define a locked account, because the case of a locked account is specific to my application. In the general case, I just need to make sure that when exceptions are caught they are handled by the `restOauthErrorHandler` bean. The default implementation of this bean will handle errors equivalently to

````groovy
def errorParamValue = e.cause?.hasProperty('code') ? e.cause.code : 500
errorParams = "&error=${errorParamValue}&error_description=${e.message?.encodeAsURL()?:''}"
errorParams += "&error_code=" + e.cause ? e.cause.class.simpleName : e.class.simpleName 
````
This is almost backwards-compatible with 1.5.2 except the `message` parameter has been renamed to `error_description` to conform with the RFC, are you OK with this or would you prefer if I didn't change the parameter name (your choice).

> If you have further doubts, we can continue the discussion in Gitter.

Hopefully there won't need to be too much further discussion, I'll logon to Gitter if necessary

**Comment by alvarosanchez** [comment]
Version `1.5.3-SNAPSHOT` has been published. Please have a look at it.
