### ISSUE TITLE
Grails 3 support?

### ISSUE THREAD

**Issue by ararog** [alvarosanchez/grails-spring-security-rest#240]
I've been trying to add this plugin to grails 3 project, but looks like it isn't supported yet, can someone please confirm?

**Comment by hugheba** [comment]
+1 for Grails 3 support

**Comment by ejaz-ahmed** [comment]
@alvarosanchez can you create grails3 branch in this repo? I am planning to work on this port in next week.

**Comment by alvarosanchez** [comment]
Duplicates #233 

The plugin will definitely be upgraded, but we need to get first a Grails 3 compatible spring-security-core.

**Comment by alvarosanchez** [comment]
2.0.0.M1 published: http://alvarosanchez.github.io/grails-spring-security-rest/2.0.0.M1/
