### ISSUE TITLE
Return the reason of login failure to clients

### ISSUE THREAD

**Issue by ertanden** [alvarosanchez/grails-spring-security-rest#243]
I asked this question on stackoverflow and was able to resolve my problem with a workaround:
http://stackoverflow.com/questions/33691333/how-to-get-the-reason-of-login-failure-in-clients-while-using-grails-spring-secu

But, it would be nice if we could configure the plugin to return the reason of the login failure, including a custom reason message.

Example config can be something like:

badCredentialsMessage = "Username or password incorrect"
lockedMessage = "Account locked for 5 minutes because of too many attempts. Please try later".

**Comment by alvarosanchez** [comment]
As there is an easy workaround, this won't be implemented.

See http://stackoverflow.com/a/33692352/2923710 for details.
