### ISSUE TITLE
Fine-Grained annotation security rule not working

### ISSUE THREAD

**Issue by fagnernostrum** [alvarosanchez/grails-spring-security-rest#244]
My application is using grails-spring-security-rest plug-in (mapped to /auth/login and /auth/logout endpoints). I want for one of my actions a non-authenticated access. To acomplish this I tried the @Secured(['permitAll']) for this action.
But in a request to this action, the application is returning HTTP code 401.

curl -i -X GET -H "Content-Type: application/json" -d '{"name":"usertocreate", "password":"123456", "email":"foo@organization.com"}' http://localhost:8080/MyApp/api/v1/user/create

Response:
HTTP/1.1 401 Unauthorized
Server: Apache-Coyote/1.1
WWW-Authenticate: Bearer
Content-Length: 0
Date: Fri, 13 Nov 2015 13:37:03 GMT

Is there some additional configuration and/or misconfiguration? The Config.groovy properties regarding security, UrlMappings.groovy and the controller are attached.
[Config.txt](https://github.com/alvarosanchez/grails-spring-security-rest/files/34079/Config.txt)
[UserController.txt](https://github.com/alvarosanchez/grails-spring-security-rest/files/34081/UserController.txt)
[UrlMappings.txt](https://github.com/alvarosanchez/grails-spring-security-rest/files/34082/UrlMappings.txt)

**Comment by alvarosanchez** [comment]
Can you please post the debug logs of such request?

**Comment by fagnernostrum** [comment]
The request's debug log is attached. I also tried to configure this action for ROLE_ANONYMOUS (the filters seems to ask for it by the log result), but got the same result.

Doing some search on internet, it seems to be related to namespace use in spring security core...

[request_debug.txt](https://github.com/alvarosanchez/grails-spring-security-rest/files/36645/request_debug.txt)

**Comment by fagnernostrum** [comment]
Sorry, i forgot to add I'm using grails 2.5.1

**Comment by alvarosanchez** [comment]
The problem here is:

    2015-11-17 10:20:53,072 [http-bio-8080-exec-4] DEBUG intercept.FilterSecurityInterceptor  - Secure object: FilterInvocation: URL: /api/v1/user/create; Attributes: [_DENY_]

Which means that Spring Security Core hasn't detected any secure annotation.

Can you please to try explicitly with `spring-security-core:2.0-RC6` in your `BuildConfig.groovy`?

**Comment by fagnernostrum** [comment]
I tried now with spring-security-core:2.0-RC6, but now the filter invocation seems to expect [isAuthenticated()] for the action.
[request_debug_RC6.txt](https://github.com/alvarosanchez/grails-spring-security-rest/files/36668/request_debug_RC6.txt)
[BuildConfig.txt](https://github.com/alvarosanchez/grails-spring-security-rest/files/36669/BuildConfig.txt)

**Comment by fagnernostrum** [comment]
An additional information is that actually the project has two distinct controllers for the same entity. One for deal with browser access and other for mobile REST request. The controller for mobile request is the one under the namespace listed previously. 
Can it cause a potential security role conflict?

**Comment by alvarosanchez** [comment]
Namespaced controllers are supposed to be working in RC6.

Please set this debug level:

trace 'grails.plugin.springsecurity'

And paste here the startup output

**Comment by fagnernostrum** [comment]
The startup output is attached. In fact, it lists /api_v1:user/create as 'permitAll' role, but when I do the request, still returns
[start_output.txt](https://github.com/alvarosanchez/grails-spring-security-rest/files/40166/start_output.txt)
 the output of the previous request_debug_RC6.txt file, with /api/v1/user/create; Attributes: [isAuthenticated()]

**Comment by tgsoverly** [comment]
I was able to accomplish something similar:

### Controllers:

On methods to allow anon:

    	@Secured("permitAll")

On methods to secure

    	@Secured("ROLE_USER")  //ADMIN in your case

### Config

Filters: 

	[pattern: '/api/login',      filters: stateless],
	[pattern: '/api/**',         filters: statelessWithAnon],

I have nothing in staticRules, leave everything to white listing methods with "permitAll"
