### ISSUE TITLE
Spring security rest plugin for Grails 3

### ISSUE THREAD

**Issue by alicehelen** [alvarosanchez/grails-spring-security-rest#245]
Please provide the spring security rest plugin to use with Grails 3. Should we use springboot instead if plugin is not available for Grails 3

**Comment by alvarosanchez** [comment]
Duplicates #233 

The plugin will be updated. ETA this year.

**Comment by alvarosanchez** [comment]
2.0.0.M1 published: http://alvarosanchez.github.io/grails-spring-security-rest/2.0.0.M1/
