### ISSUE TITLE
BAD request while logging in, [CORS] [HTTPS]

### ISSUE THREAD

**Issue by nikhil-bhandari** [alvarosanchez/grails-spring-security-rest#246]
I have just started using Spring Security REST plugin to work with angularjs and grails. 

Just to give a background I am trying to login on https from http angular app, I know its not that secure but I have to get this working without switching the whole site to https. 

Now coming to the issue, whenever I hit the api url for login "https://localhost:8443/api/v2/login" I get a bad request and following info in the logs. 

```
DEBUG rest.RestAuthenticationFilter  - Actual URI is /api/v2/login; endpoint URL is /api/v2/login
DEBUG rest.RestAuthenticationFilter  - Applying authentication filter to this request
DEBUG credentials.DefaultJsonPayloadCredentialsExtractor  - No JSON body sent in the request
DEBUG rest.RestAuthenticationFilter  - Username and/or password parameters are missing.
DEBUG rest.RestAuthenticationFilter  - Setting status to 400
```

But if I try it using "http://localhost:8080/api/v2/login" it works fine. Can someone point me in the right direction to get this working?

Following is my Config

```
cors.enabled = true
cors.url.pattern = '/api/v2/login/*'
cors.headers = [
        'Access-Control-Allow-Origin'     : '*',
        'Access-Control-Allow-Credentials': true,
        'Access-Control-Allow-Headers'    : 'origin, authorization, accept, content-type, x-requested-with',
        'Access-Control-Allow-Methods'    : 'GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS',
        'Access-Control-Max-Age'          : 3600
]


grails.plugin.springsecurity.rest.login.active = true
grails.plugin.springsecurity.rest.login.endpointUrl = "/api/v2/login"
grails.plugin.springsecurity.rest.logout.endpointUrl = '/api/v2/logout'
grails.plugin.springsecurity.rest.login.failureStatusCode = 401
grails.plugin.springsecurity.rest.login.usernamePropertyName = "email"
grails.plugin.springsecurity.rest.login.passwordPropertyName = "password"

```

And just for reference angular side code

This doesn't work, it results in BAD request with logs mentioned above

```
            $http.post('https://localhost:8443/api/v2/login', {
                'email': user.email,
                'password': user.password
            })

```

This works Fine

```
            $http.post('http://localhost:8080/api/v2/login', {
                'email': user.email,
                'password': user.password
            })

```

Am I missing something while making the call? Do I need to set something to forward the POST parameters?

**Comment by alvarosanchez** [comment]
In order for `DefaultJsonPayloadCredentialsExtractor` to find credentials in the request:
* Content type must be set to `application/json`.
* Request body must include a JSON body, in your case like: `{"email":"foo", "password":"bar"}`.

Can you please make sure the above conditions are met? Could you also try using command-line (eg: `curl`).

**Comment by nikhil-bhandari** [comment]
Thanks for the prompt reply @alvarosanchez 

These are the request headers that I see after inspecting the request.

```
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,sv;q=0.6
Connection:keep-alive
Content-Length:67
Content-Type:application/json;charset=UTF-8
Host:localhost:8443
Origin:http://localhost:8080
Referer:http://localhost:8080/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
```

 I'll still try to make this request using CURL.

**Comment by alvarosanchez** [comment]
Is it a `POST` request? Does the request include the JSON body?

**Comment by nikhil-bhandari** [comment]
Yes it is a POST request with JSON body. I tried following CURL command and it didn't work.

```curl 'https://localhost:8443/api/v2/login' -H 'Origin: http://localhost:8080' -H 'Content-Type: application/json' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:8080/' --data '{"email":"my@email.com","password":"password"}' --insecure```

**Comment by alvarosanchez** [comment]
Could you please upload somewhere the Grails part that reproduces the issue?

**Comment by nikhil-bhandari** [comment]
Thanks for looking. I'll try to isolate this in a new project, I just wanted to ensure that I wasn't missing a trivial thing.

 I'll quickly create the project and try to fix it, and come back if it doesn't work.

**Comment by alvarosanchez** [comment]
One thing you can do instead is to run the app in debug mode, and set a breakpoint in https://github.com/alvarosanchez/grails-spring-security-rest/blob/develop/src/groovy/grails/plugin/springsecurity/rest/credentials/AbstractJsonPayloadCredentialsExtractor.groovy#L31

An exception is surely thrown there, so if I know which one I can try to fix it.

**Comment by nikhil-bhandari** [comment]
ok, this is the exception that I get.

```
java.lang.IllegalStateException: getInputStream() has already been called for this request
```

**Comment by nikhil-bhandari** [comment]
I tried it on a new app but I couldn't get basic rest features working there. Now looking for a sample app to try this. Did you find anything?

**Comment by nikhil-bhandari** [comment]
It was because of a CustomFilter in my app. Closing the issue. 

Thanks for the help!

:D
