### ISSUE TITLE
Expiration time cannot be bigger than Integer.MAX_VALUE

### ISSUE THREAD

**Issue by mradzinski** [alvarosanchez/grails-spring-security-rest#247]
It seems that given the current implementation, *generateAccessToken* method only allows for expiration to be less or equal to Integer.MAX_VALUE, thus if we set an expiration time of 9223372036854775807 it will overflow. I know this seems a bit odd (who wants to have a 1000 or more years token?) but given that expiration time is expressed in milliseconds from *now*, I think the parameter should be of type *Long* instead of *Integer* to provide a bit more flexibility:

    AccessToken generateAccessToken(UserDetails details, Long expiration)

**Comment by alvarosanchez** [comment]
Not that easy as I thought it would be to fix. There is no support for `longValue.seconds` in Groovy's `TimeCategory`.

Also note that the expiration is in seconds, so that gives you 292471208677 years. That's probably enough for all forms of life in the universe ;)
