### ISSUE TITLE
Add CORS support for plugin version 2.x

### ISSUE THREAD

**Issue by mengelhart** [alvarosanchez/grails-spring-security-rest#256]
Hi -

I've been successfully using the 2.x grails version of this plugin for a while now but in attempting to move to Spring Security 3.0.x and the plugin version 2.0.x I'm not understanding something about how the CORS mapping is supposed to work.   I've tried both the servlet filter standalone code and the plugin but neither of them seem to intercept the Spring security login URL itself so any attempt to POST credentials to /auth/login (which is what i have it mapped to in my application.groovy) returns a 405 Method Not Allowed for OPTIONS http method. 

Is there some configuration necessary to allow Spring Security to allow OPTIONS on it's login calls?   This "just worked" in the grails 2.x + CORS integration. 

Thanks
Mike

**Comment by rkimaoui** [comment]
Same Here. Help please !

**Comment by alvarosanchez** [comment]
I'll have a look to see if I can easily include something in the plugin.

**Comment by rkimaoui** [comment]
I found the solution; when using spring security plugin with grails 3, you have to specify server contextPath in Application.groovy;   
```
server.contextPath= "/myApi"
```

Now everything is working with Cors Filter.

Thx Alvaro.

**Comment by AleksanderGrzybowski** [comment]
I have the same problem, I am trying to port a working application from grails 2 to 3 and 405 is returned all the time. @rkimaoui I think you are right, adding this property to application.groovy changes something (turns 405 into 404 in my case, at least). In my case the whole app is REST-based using standard controller/action mappings, maybe you know what could I use for .contextPath?

**Comment by ejaz-ahmed** [comment]
Guys, I am using CORS interceptor available in grails 2 CORS plugin github repo and I've not faced any issue. If anyone needs a sample application, I can workout and put that in some github repo. Let me know if you need any?

**Comment by mengelhart** [comment]
Are you using a Grails 2 app?  If so that's never been a problem.   We're having trouble with Grails 3 and the latest plugin which removed CORS support. 

I still can't get this to work either.. If anyone wouldn't mind sharing their application.groovy and CORS interceptor code I'd appreciate it.   I tried both the Grails 3 CORS plugin and put the actual interceptor in my code and while the interceptor gets called for all requests when I hit the Grails app directly, when my AngularJS app makes a request to the grails app the CORS interceptor doesn't fire for OPTIONS calls so I'm effectively blocked still.     The server.contextPath did allow my code to make OPTIONS calls but the response headers are still missing the CORS Headers.   If anyone has a sample to share I'd *REALLY* appreciate as I'm under a time crunch and have been messing around with this for almost a month with no luck.

**Comment by ejaz-ahmed** [comment]
@mengelhart  here is a demo app using grails 3 and spring  security rest plugin https://github.com/ejaz-ahmed/grails3-springsecurity-rest-demo

This application is just replica of our main app's authentication system. We are also using angular with our grails3 app. We use POST for login. Our application does not use OPTIONS method at all. Ours was also a grails 2.x app and we upgraded it to grails 3.0.11 when M1 of this plugin was released. I can't understand why are you using OPTIONS method for login?  Our login and other stuff is working fine with this plugin and a CorsFilter in src folder. If you have any issues or want more information, do let me know.

**Comment by mengelhart** [comment]
@ejaz-ahmed  - thank you very much for the demo -  I'll check it out.
I'm not explicitly using OPTIONS, my understanding is that the browser does an OPTIONS check when doing cross origin application.  When we POST to login Chrome is doing an OPTIONS check and then failing at that point.   I agree I'd rather not do OPTIONS here as it's not necessary so maybe I've got something configured incorrectly.    Are you deploying your angular app from inside your grails application or using something like grunt to serve it on a different port (i.e. using CORS to allow cross domain calls).

**Comment by ejaz-ahmed** [comment]
Yes. We are using grunt to serve angular front end. Our grails app is gsp free. Got it. Yes we also hit this issue as I am in charge of backend and passed out upgraded app to front end guys and they fired back with this issue. Only then I looked back into it and scanned updated docs of this plugin. Thanks to @alvarosanchez for writing excellent docs. Docs pointed out to CorsFilter code and it just worked without any problem. This code should work for you as well as our app is well tested on all famous browsers.

**Comment by mengelhart** [comment]
thanks @ejaz-ahmed .  still no go here though.  I downloaded and ran your sample grails app as is and wrote a quick and dirty angular app to test hitting http://localhost:8080/api/login and I'm getting the following in Chrome if you inspect which is what I've been seeing all along with our grails/angular app.   As I mentioned the OPTIONS call happens by the browser, not anything I'm doing in Angular.

![screen shot 2016-01-18 at 3 14 11 pm](https://cloud.githubusercontent.com/assets/722897/12401706/32b79b16-bdf6-11e5-93b2-04913ca9337e.png)

Here's the angular code if anyone sees something I'm doing wrong here (I basically just created an angular-seed project and added this to the sample controller)
```
.controller('View1Ctrl', ['$http', function($http) {
	var vm = this;
	vm.authenticate = function() {
		console.log(vm);
		$http.post('http://localhost:8080/api/login',
							 {username: vm.username, password: vm.password})
				.success(function(result){
						$scope.result = result;
						headers['X-Auth-Token'] = result.token;
				})
				.error(function(error){
						$scope.result = error;
				});
	}
	
	
}]);
```

**Comment by mengelhart** [comment]
@ejaz-ahmed I think I figured it out., your demo app wasn't referencing the CORS filter code in resources.groovy

I created an app from scratch and configured it and that step seemed to be the thing that was missing from your sample.   Anyway - it's resolved now for me -I just now have to port these configurations over to my application.   I'll post my test app  on github when i get a chance.

thanks again for the help.

**Comment by ejaz-ahmed** [comment]
@mengelhart I don't know anything about angular and copied these parts from our production app. Sorry for this mistake and I am happy that you dot your stuff done. Cheers.

**Comment by thecodesmith** [comment]
@mengelhart I'm seeing exactly the same issue you posted in your screenshots. Were you able to get this working? If so, I'd love to see your test app code. Many thanks for helping me get this far!

**Comment by ejaz-ahmed** [comment]
@thecodesmith yes. He was successful. You can try this repo  https://github.com/ejaz-ahmed/grails3-springsecurity-rest-demo and it should work for you as well.

**Comment by mengelhart** [comment]
@thecodesmith   here's my sample code..  It should have everything you need in Grails 3.. You'll need to supply your own angular/UI code

https://github.com/mengelhart/AngularRestLoginGrails3

**Comment by thecodesmith** [comment]
@mengelhart @ejaz-ahmed Thanks so much for your help, I was finally able to get it working!

**Comment by bogog87** [comment]
@ejaz-ahmed @mengelhart  im using grails 3.1.1 and this filter wasnt working when i setted up the war on my tomcat instance. so i had to make some changes at the resources definition to apply this filter work at tomcat instances. was researching and looking for a solution for some time. Before the cors plugin for grails 2.x was working with the definiton of the filter in the web.xml. so the filter was applied properly. 
to make it work with grails 3.X i found a solution like this:

import test.CorsFilter
import org.springframework.core.Ordered
import org.springframework.boot.context.embedded.FilterRegistrationBean

// this import is valid

// Place your Spring DSL code here
beans = {
    corsFilter(FilterRegistrationBean){
        filter = bean(CorsFilter)
        urlPatterns = ['/*']
        order = Ordered.HIGHEST_PRECEDENCE
    }
}

here are related posts: http://stackoverflow.com/questions/28430675/grails-3-manipulating-web-xml

**Comment by ejaz-ahmed** [comment]
@bogog87 My app is in production and using tomcat as runnable jar on tomcat 8. Which version of tomcat are you using? Can we make a concise example of this in single repo which works in all environments? It would be better if you submit a PR to @mengelhart repo.

**Comment by MatthiasRacke** [comment]
Hi,
filters are deprecated as of Grails 3, but using an interceptor seems not to work for /api/login. Is there a solution for interceptor?

Thx Matthias

**Comment by mengelhart** [comment]
@MatthiasRacke  - 
Grails filters may be deprecated but the CorsFilter in my sample code above uses a ServletFilter which is different and the servlet spec (as far as I know) hasn't deprecated ServletFilter

**Comment by appcela** [comment]
Just FYI, [grails3-cors-interceptor](https://github.com/appcela/grails3-cors-interceptor) has been updated to include a SpringSecurityCorsFilter (this is a Spring Security filter) to fix this issue. 

See https://github.com/appcela/grails3-cors-interceptor-spring-security-rest-sample-app for more info.

- [Working with Spring Security REST Plugin](https://github.com/appcela/grails3-cors-interceptor-spring-security-rest-sample-app#working-with-spring-security-rest-plugin)

**Comment by alvarosanchez** [comment]
Closing this as CORS will be supported in Grails core. See https://github.com/grails/grails-core/issues/10148
