### ISSUE TITLE
Grails 3.0.11 + 2.0.0.M1: GrailsAnonymousAuthenticationFilter - Populated SecurityContextHolder with anonymous token

### ISSUE THREAD

**Issue by wiggitamoo** [alvarosanchez/grails-spring-security-rest#258]
First of all, I love this plugin, and have it almost working. I was hoping you help me reach the last mile. 

## Problem
I'm having trouble with the correct configurations of
* grails.plugin.springsecurity.filterChain.chainMap
* @Secured in my controller

I am able to receive the correct springSecurityService.principal for the logged in user. When changing this to 

I have tried the following
![image](https://cloud.githubusercontent.com/assets/1783757/12360105/eac9181c-bb83-11e5-83d4-6cbb927671d2.png)

Either scenario, the SecurityContextHolder always stores an anonymous user even though my Bearer token is being authenticated correctly.

## Here's my setup:
* Grails 3.0.11

##### build.gradle
```
classpath "org.grails.plugins:hibernate:4.3.10.5"
...
compile "org.grails.plugins:spring-security-core:3.0.0.M2"
compile "org.grails.plugins:spring-security-rest:2.0.0.M1"
```

##### application.groovy
```groovy
// JSON Web Token (JWT)
grails.plugin.springsecurity.rest.token.storage.useJwt = true
grails.plugin.springsecurity.rest.token.storage.jwt.useSignedJwt = true
grails.plugin.springsecurity.rest.token.storage.jwt.secret = <secret>
grails.plugin.springsecurity.rest.token.storage.jwt.expiration = 3600

// Token Rendering
grails.plugin.springsecurity.rest.token.rendering.usernamePropertyName = 'login' 
grails.plugin.springsecurity.rest.token.rendering.authoritiesPropertyName = 'authorities' 

//REST SECURITY
grails {
    plugin {
        springsecurity {
            filterChain {
                chainMap = [
                        // Stateless chain
                        [
                                // allows anonymous access
                                pattern: '/api/guest/**',
                                filters: 'anonymousAuthenticationFilter,restTokenValidationFilter,restExceptionTranslationFilter,filterInvocationInterceptor'
                        ],
                        [
                                // doesn’t allow anonymous access
                                pattern: '/api/**',
                                filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'
                        ],
                        [
                                pattern: '/projectOverview/**',
                                filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'
                        ],

                        // Traditional stateful chain
                        [
                                pattern: '/**',
                                filters: 'JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter'
                        ]
                ]
            }

//            rest {
//                token {
//                    validation {
//                        enableAnonymousAccess = true
//                    }
//                }
//            }
        }
    }
}

// Added by the Spring Security Core plugin:
grails.plugin.springsecurity.userLookup.userDomainClassName = 'nwo.api.User'
grails.plugin.springsecurity.userLookup.authorityJoinClassName = 'nwo.api.UserAuth'
grails.plugin.springsecurity.authority.className = 'nwo.api.Auth'
grails.plugin.springsecurity.authority.groupAuthorityNameField = 'authorities'
grails.plugin.springsecurity.useRoleGroups = true

grails.plugin.springsecurity.controllerAnnotations.staticRules = [

        [pattern: '/', access: ['permitAll']],
        [pattern: '/error', access: ['permitAll']],
        [pattern: '/index', access: ['permitAll']],
        [pattern: '/index.gsp', access: ['permitAll']],
        [pattern: '/shutdown', access: ['permitAll']],
        [pattern: '/assets/**', access: ['permitAll']],
        [pattern: '/**/js/**', access: ['permitAll']],
        [pattern: '/**/css/**', access: ['permitAll']],
        [pattern: '/**/images/**', access: ['permitAll']],
        [pattern: '/**/favicon.ico', access: ['permitAll']]

]

grails.plugins.springsecurity.rememberMe.alwaysRemember = true
grails.plugin.springsecurity.rememberMe.persistent = true
grails.plugin.springsecurity.rememberMe.persistentToken.domainClassName = 'nwo.api.PersistentLogin'


grails.plugin.springsecurity.roleHierarchyEntryClassName = 'nwo.api.RoleHierarchyEntry'

// reject un-mapped URLs with a 403 error code
grails.plugin.springsecurity.rejectIfNoRule = true
grails.plugin.springsecurity.fii.rejectPublicInvocations = false

// makes the application easier to work with
grails.plugin.springsecurity.logout.postOnly = false

// Authentication
//grails.plugin.springsecurity.useBasicAuth = true
//grails.plugin.springsecurity.basic.realmName = "Optimal Strategix Group NWO"

// Events
grails.plugin.springsecurity.useSecurityEventListener = false

```

##### Controller
```groovy
package nwo.api

import grails.plugin.springsecurity.annotation.Secured
import grails.rest.Resource
import nwo.api.project.overview.SaveWidgetsRequest

@Secured(['permitAll'])
//@Secured(['ROLE_ADMIN'])
class ProjectOverviewController {
    static allowedMethods = [
            saveWidgets: ['POST'],
            getWidgets : ['POST']
    ]
    static responseFormats = ["json"]
    def dataSource
    def springSecurityService

    def index() { redirect(action: "getWidgets") }

    def getWidgets() {
        def principal = springSecurityService.principal
        def userId = principal.id;
        <code here ...>
        respond response
    }

    def saveWidgets() {
        // get user id from Spring Security Service
        def principal = springSecurityService.principal
        def userId = principal.id;
        <code here ...>
        respond response
    }

}
```

##### Logs
<pre>
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/projectoverview/getwidgets'; against '/api/guest/**'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/projectoverview/getwidgets'; against '/api/**'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/projectoverview/getwidgets'; against '/chart/**'
DEBUG org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/projectoverview/getwidgets'; against '/projectoverview/**'
DEBUG org.springframework.security.web.FilterChainProxy - /projectOverview/getWidgets at position 1 of 6 in additional filter chain; firing Filter: 'MutableLogoutFilter'
DEBUG org.springframework.security.web.FilterChainProxy - /projectOverview/getWidgets at position 2 of 6 in additional filter chain; firing Filter: 'RestAuthenticationFilter'
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationFilter - Actual URI is /projectOverview/getWidgets; endpoint URL is /api/login
DEBUG org.springframework.security.web.FilterChainProxy - /projectOverview/getWidgets at position 3 of 6 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
DEBUG org.springframework.security.web.FilterChainProxy - /projectOverview/getWidgets at position 4 of 6 in additional filter chain; firing Filter: 'RestTokenValidationFilter'
DEBUG grails.plugin.springsecurity.rest.token.bearer.BearerTokenReader - Looking for bearer token in Authorization header, query string or Form-Encoded body parameter
DEBUG grails.plugin.springsecurity.rest.token.bearer.BearerTokenReader - Found bearer token in Authorization header
<b>DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Token found: (token)</b>
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Trying to authenticate the token
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationProvider - Trying to validate token (token)
<b>DEBUG grails.plugin.springsecurity.rest.token.storage.jwt.JwtTokenStorageService - Successfully verified JWT</b>
DEBUG grails.plugin.springsecurity.rest.token.storage.jwt.JwtTokenStorageService - Trying to deserialize the principal object
DEBUG grails.plugin.springsecurity.rest.token.storage.jwt.JwtTokenStorageService - UserDetails deserialized: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationProvider - Now is Fri Jan 15 12:05:14 EST 2016 and token expires at Fri Jan 15 13:05:06 EST 2016
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationProvider - Expiration: 3591
<b>DEBUG grails.plugin.springsecurity.rest.RestAuthenticationProvider - Authentication result: grails.plugin.springsecurity.rest.token.AccessToken(accessToken:(token), expiration:3591, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER, super:grails.plugin.springsecurity.rest.token.AccessToken@fec73759: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_ADMIN, ROLE_USER)</b>
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Token authenticated. Storing the authentication result in the security context
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Authentication result: grails.plugin.springsecurity.rest.token.AccessToken(accessToken:(token), expiration:3591, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER, super:grails.plugin.springsecurity.rest.token.AccessToken@fec73759: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_ADMIN, ROLE_USER)
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Continuing the filter chain
DEBUG org.springframework.security.web.FilterChainProxy - /projectOverview/getWidgets at position 5 of 6 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
DEBUG org.springframework.security.web.FilterChainProxy - /projectOverview/getWidgets at position 6 of 6 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
DEBUG org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Secure object: FilterInvocation: URL: /projectOverview/getWidgets; Attributes: [permitAll]
<b>DEBUG org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Previously Authenticated: grails.plugin.springsecurity.rest.token.AccessToken(accessToken:(token), expiration:3591, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER, super:grails.plugin.springsecurity.rest.token.AccessToken@fec73759: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_ADMIN, ROLE_USER)</b>
DEBUG org.springframework.security.access.hierarchicalroles.RoleHierarchyImpl - getReachableGrantedAuthorities() - From the roles [ROLE_ADMIN, ROLE_USER] one can reach [ROLE_USER, ROLE_ADMIN] in zero or more steps.
DEBUG org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Authorization successful
DEBUG org.springframework.security.web.access.intercept.FilterSecurityInterceptor - RunAsManager did not change Authentication object
DEBUG org.springframework.security.web.FilterChainProxy - /projectOverview/getWidgets reached end of additional filter chain; proceeding with original chain
DEBUG grails.plugin.springsecurity.rest.token.bearer.BearerTokenReader - Looking for bearer token in Authorization header, query string or Form-Encoded body parameter
DEBUG grails.plugin.springsecurity.rest.token.bearer.BearerTokenReader - Found bearer token in Authorization header
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Token found: (token)
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Trying to authenticate the token
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationProvider - Trying to validate token (token)
DEBUG grails.plugin.springsecurity.rest.token.storage.jwt.JwtTokenStorageService - Successfully verified JWT
DEBUG grails.plugin.springsecurity.rest.token.storage.jwt.JwtTokenStorageService - Trying to deserialize the principal object
DEBUG grails.plugin.springsecurity.rest.token.storage.jwt.JwtTokenStorageService - UserDetails deserialized: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationProvider - Now is Fri Jan 15 12:05:14 EST 2016 and token expires at Fri Jan 15 13:05:06 EST 2016
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationProvider - Expiration: 3591
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationProvider - Authentication result: grails.plugin.springsecurity.rest.token.AccessToken(accessToken:(token), expiration:3591, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER, super:grails.plugin.springsecurity.rest.token.AccessToken@fec73759: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_ADMIN, ROLE_USER)
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Token authenticated. Storing the authentication result in the security context
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Authentication result: grails.plugin.springsecurity.rest.token.AccessToken(accessToken:(token), expiration:3591, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER, super:grails.plugin.springsecurity.rest.token.AccessToken@fec73759: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_ADMIN, ROLE_USER)
DEBUG grails.plugin.springsecurity.rest.RestTokenValidationFilter - Continuing the filter chain
<b>DEBUG grails.plugin.springsecurity.web.filter.GrailsRememberMeAuthenticationFilter - SecurityContextHolder not populated with remember-me token, as it already contained: 'grails.plugin.springsecurity.rest.token.AccessToken(accessToken:(token), expiration:3591, refreshToken:null, principal:grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER, super:grails.plugin.springsecurity.rest.token.AccessToken@fec73759: Principal: grails.plugin.springsecurity.userdetails.GrailsUser@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_ADMIN,ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_ADMIN, ROLE_USER)'
DEBUG org.springframework.security.web.context.HttpSessionSecurityContextRepository - No HttpSession currently exists
DEBUG org.springframework.security.web.context.HttpSessionSecurityContextRepository - No SecurityContext was available from the HttpSession: null. A new one will be created.</b>
<b style="color:red">DEBUG grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter - Populated SecurityContextHolder with anonymous token: 'grails.plugin.springsecurity.authentication.GrailsAnonymousAuthenticationToken@dc41564: Principal: org.springframework.security.core.userdetails.User@dc730200: Username: __grails.anonymous.user__; Password: [PROTECTED]; Enabled: false; AccountNonExpired: false; credentialsNonExpired: false; AccountNonLocked: false; Granted Authorities: ROLE_ANONYMOUS; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS'</b>
DEBUG grails.plugin.springsecurity.rest.RestAuthenticationFilter - Actual URI is /projectOverview/getWidgets; endpoint URL is /api/login
</pre>

Please let me know if you see anything which would be causing the SecurityContextHolder to be populated with an anonymous token which causes the springSecurityService.principal to be wrong in the controller.

**Comment by Schlogen** [comment]
Use the latest version of spring security and try again

`compile "org.grails.plugins:spring-security-core:3.0.0.M2"`

Should be

compile "org.grails.plugins:spring-security-core:3.0.3"

**Comment by wiggitamoo** [comment]
Yessir, 3.0.3 is working as expected. Thanks!
