### ISSUE TITLE
Hook addition for sending extra data in login response

### ISSUE THREAD

**Issue by bluetoothbites** [alvarosanchez/grails-spring-security-rest#259]
Would be great if there is some hook to add extra data in login response (it could be part of token or separate elements in the login response) - like full user name, profile url or even profile pic data bytes. This would save a round trip to the server to pull additional data that is usually needed immediately after login.

**Comment by ejaz-ahmed** [comment]
Wouldn't it be an overkill if you don't need this data?

**Comment by alvarosanchez** [comment]
Login response would be generated just on login request, and not on every request. And the hook will be optional.

**Comment by mannejkumar** [comment]
Can i know when it will be available?

**Comment by alvarosanchez** [comment]
This has been always possible by registering your own `AccessTokenJsonRenderer`: http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/index.html#_disabling_bearer_tokens_support_for_full_response_customisation
