### ISSUE TITLE
Server to server Authentication

### ISSUE THREAD

**Issue by rkimaoui** [alvarosanchez/grails-spring-security-rest#260]
Hi Alvaro,
First of all, thank you for this great plugin.
I would like to implement a server to server communication by passing an api key in the url (HTTP Basic Authentication), like:
http://api.example.com/resource/id?apiKey=xxxxxxxx

Can i achieve this use case using your plugin ? or maybe with oauth ?
Need your advice please.

Regards,
Reda

**Comment by alvarosanchez** [comment]
Please post such usage questions on StackOverflow.

Thanks!
