### ISSUE TITLE
Question: Overriding the user creds extractor changes the login url?

### ISSUE THREAD

**Issue by JakeRuth** [alvarosanchez/grails-spring-security-rest#263]
Hello everyone,

So I am really loving this plugin, I just have one question about some weird behavior I saw that I didn't see an answer for in the documentation.  

I followed section 7.1 of the user guide, it's pretty straight forward.  All I want to do is lowercase the email that comes in, so I made a copy of that class and registered it as a bean.

I think it did change the extractor because I saw a change in behavior, but now what I expected.

Here's what happened before the change (default extractor) when I requested api/login with an invalid username/pass combo.

```
HTTP/1.1 401 Unauthorized
Content-Length: 0
Date: Fri, 26 Feb 2016 12:55:49 GMT
Server: Apache-Coyote/1.1
WWW-Authenticate: Bearer
```

After the change, this is what happened after I sent the same request (request has uppercase username, it's lowercased in the DB so I'd expect for this to go through and generate the token)

```
HTTP/1.1 302 Found
Content-Length: 0
Date: Fri, 26 Feb 2016 13:03:10 GMT
Location: http://localhost:8080/Greedy/login/auth
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=20939ACFDDF1708637EDF36641F36594; Path=/Greedy/; HttpOnly
```

Can anyone shed some light on what is happening here? Thank you so much!!!

Grails version: 2.4.4
Spring Security Rest Plugin version: 1.5.2

- Jake

PS FWIW I am using the JWT token method for generating the token.

**Comment by alvarosanchez** [comment]
That response is generated by Spring Security's standard filter, which redirects you to the login page. When using the stateless chain the filter is not in place.

I'd need to see your configuration, all details about how the request is made, and `DEBUG` level output of the server.

**Comment by JakeRuth** [comment]
Thank you for your reply @alvarosanchez 
Unfortunately I am too busy to dig into this further, I ended up working around the issue.  I will put this in my backlog and hopefully I can find time to get around to it.

I will close this for now so it doesn't linger around, perhaps someone else will run into this and reopen the issue, sorry for this lame response.
