### ISSUE TITLE
OAuth for Javascript frontend vs Mobile App 

### ISSUE THREAD

**Issue by ask10000** [alvarosanchez/grails-spring-security-rest#270]
The documentation for OAuth says this plugin takes care of OAuth for Javascript frontend web apps. However, the plugin is awesome for securing REST that I am using it for my mobile app, but there is no instruction about how to integrated OAuth with a mobile app and this plugin. Has anyone figured out the OAuth part integration with say Google and Facebook auth? My guess has been that an ideal flow for this would be - 
1.we handle the facebook/google authentication separately, 
2.we receive FB/Google oauth token 
3. we pass on the FB/Google oauth token to this plugin (at backend), 
4. the plugin checks with fb/google and validates the oauth token 
5. on successful validation of the oauth token, the plugin generates the app token
6. mobile app stores the token and sends it with every subsequent request.

Is this the correct flow? If yes, how do we use it? THere is no instruction in the guide. Will really help.

**Comment by alvarosanchez** [comment]
The OAuth delegation is an HTTP redirect based flow. Therefore, to use it in a mobile app you would need to have a WebView/embedded browser, which might not be the best user experience compared with native logins using Facebook/Google SDK's.

The flow you are describing is impossible because this plugin will only validate tokens issued by the plugin itself.

**Comment by machador** [comment]
Hi @alvarosanchez. I am having the same situation to solve as @ask10000 

When you say the flow is impossible, it doesn't appear to be actually. 

The flow proposed makes sense: Authentication to Facebook is solved in the mobile app, and the, Facebook access_token is sent to the server for validation along with username(or user id). Then, the server validates he can access data from user using the provided token, and issues a token for our app itself as usual.

**Comment by alvarosanchez** [comment]
As I said, this will only work if you use a WebView or similar. IMHO, using the native Facebook login offers a much better user experience.

**Comment by machador** [comment]
But that's actually the question. What should be the flow using the plugin if the native Facebook login is used? Is there a way once the mobile app natively gets the facebook token, use the REST plugin to authenticate? 

The proposed flow seems the way to go (or something around those lines). But currently there is no way of including the Fb/Google/etc authentication directly in the mobile app and then using the REST plugin to authenticate our api.

**Comment by snimavat** [comment]
+ 1 for the mobile clients support
