### ISSUE TITLE
Login URL with trailing '/' fails

### ISSUE THREAD

**Issue by ebernie** [alvarosanchez/grails-spring-security-rest#278]
To reproduce, attempt a POST request to http://server/api/login/. This results in 401. The failure occurs in RestAuthenticationFilter:

        `if (actualUri == endpointUrl) { // <-- this fails

            log.debug "Applying authentication filter to this request"`

Using version 2.0.0.M2.

**Comment by alvarosanchez** [comment]
The behaviour is expected, as `"http://server/api/login/" != "http://server/api/login"`.

Either change the login endpoint URL to include the trailing slash, or remove it in the client side.
