### ISSUE TITLE
Possible issue with JWT length and Outlook

### ISSUE THREAD

**Issue by florent-blanvillain** [alvarosanchez/grails-spring-security-rest#282]
Hi,

I'm getting a lot of complaints from users using outlook mail client. They can't authenticate with the jwt token generated by the plugin.

I do not reproduce the problem with the links I sent them (using gmail for example).
Unfortunately I can't test with outlook, but I never got complaints from users who are not using outlook.

Could it be the length of the generated token ? From what I have read, it seems so. 

A complaint I got this morning involves a link sent by email with a length of 1281 characters.

How to reduce the length of the jwt token ? 
Is the jwt secret used to sign the token a factor of its length ? 
If I hook in the jwt token alter the generation and make it smaller, is there a way to maintain compatibility with previously sent tokens ?

I'm using signed jwt, plugin v1.5.2 with grails 2.4.5.

Thank you

**Comment by alvarosanchez** [comment]
The JWT tokens are certainly long. One thing you can do is to shorten yourself the links before sending them by email. That's gonna be much easier than any other alternative you described.
