### ISSUE TITLE
Getting ROLE_NO_ROLES by JWT token 

### ISSUE THREAD

**Issue by mayankraipure** [alvarosanchez/grails-spring-security-rest#283]
DB: H2
grails: 3.1.6
security rest : org.grails.plugins:spring-security-rest:2.0.0.M2

{
  "username": "admin",
  "roles": [
    "ROLE_NO_ROLES"
  ],
  "token_type": "Bearer",

**Comment by alvarosanchez** [comment]
That will depend on the actual roles the user has as per your authentication provider, but that has nothing to do with this plugin.

**Comment by ferudev** [comment]
I've the same problem, but i use:
Grails 3.2.6 
DB Plugin: org.grails.plugins:mongodb
Security Rest: org.grails.plugins:spring-security-rest:2.0.0.M2

Roles and Relations (UserRole) stored correctly in DB (ex. ROLE_ADMIN and ROLE_USER). I created them in bootstrap file with this code:

```
def adminRole = new Role(authority: 'ROLE_ADMIN').save()
def userRole = new Role(authority: 'ROLE_USER').save()

def testUser1 = new User(username: 'me1', password: 'password').save()
def testUser2 = new User(username: 'me2', password: 'password').save()

UserRole.create testUser1, adminRole, true
UserRole.create testUser2, userRole, true
```
