### ISSUE TITLE
JWT Refresh Token - Prechecks

### ISSUE THREAD

**Issue by umakot1974** [alvarosanchez/grails-spring-security-rest#285]
Is there any prechecks that can be done before issuing new access token when refresh token is presented ?

How can I use the current JWT mechanism and have a "pre-check" on a few things when ever Refresh token is presented for eg: I want to store a date "userpasswd_auth_date" on user object. 

The implementation logic is to set the "userpasswd_auth_date" when ever the user changes the password or gets a new role in the system or something that requires us to force the user to have a username/password authentication. 

When client is presenting a token that is older than "userpasswd_auth_date", then force the user to login with username,password credentials else refresh token can work. 

how should I implement this kind of logic ? I am wondering if someone has already done this kind of validation.

**Comment by FiscalTiger** [comment]
Also very interested in achieving a similar result, but I cannot seem to override the current RestOauthController.

**Comment by alvarosanchez** [comment]
At the moment there is no place to hook into that method. The way of implementing this would be to create your own controller action (you can even possibly inherit from `RestOauthController`).

Then, remap the action:

    "/oauth/access_token"(controller: 'myOauthController', action: 'accessToken')
