### ISSUE TITLE
Always 401 when debugging in eclipse

### ISSUE THREAD

**Issue by majkelo** [alvarosanchez/grails-spring-security-rest#290]
| Grails Version: 3.2.0.M1
| Groovy Version: 2.4.6
| JVM Version: 1.8.0_91
When I run app by eclipse mars IDE,  gradle task _bootRun_ it works great, but when I try to debug it by:

- Spring Boot App Debug configuration
- Java Application debug configuration

application starts, breakpoints works (checked in _bootstrap.groovy_) but I got always **401** (just like _conf/application.groovy_ and its interceptUrlMap was never processed).

**Comment by majkelo** [comment]
I found workaround by moving all entries from _conf/application.groovy_ to _conf/application.yml_.

**Comment by alvarosanchez** [comment]
Closing as per last comment
