### ISSUE TITLE
How can I get token for user?

### ISSUE THREAD

**Issue by akozel** [alvarosanchez/grails-spring-security-rest#291]
Hi,
I develop back-emd for mobile application.
We want to use REST auth + GOOGLE.

Front-end will send me google token, then I will check that.
Then we want to get token for our app and send them to a client.

**How can I get token for user that I want to be authorized?**

**Comment by akozel** [comment]
I see that there is method
`tokenGenerator.generateAccessToken(UserDetails principal)`

but how can I convert MyUser to the UserDetails?

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

You can also try with asking in the [`#spring-security-rest` channel in Slack](https://grails.slack.com/messages/spring-security-rest).
