### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by alvarosanchez** [alvarosanchez/grails-spring-security-rest#292]
- Include a tutorial section describing how to integrate the plugin into an application, step by step.
- Gather all links to sample applications and or articles.

**Comment by m3lD** [comment]
Hello, I'm starting a API REST using grails and one of the requirements is authentication with Facebook.  I found  [this](http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/index.html#_delegating_authentication_to_oauth_providers) on the documentation but unfortunately is not too clear. My question is if there is any other place where I can find an example or some guide?.

Thanks!

**Comment by alvarosanchez** [comment]
Articles found:
* https://www.inshikos.com/blogs/80/dev/cors-enabled-rest-api-on-grails-for-cordova-apps-using-jwt-auth-tokens
* http://giri-tech.blogspot.com.es/2016/06/create-secured-restful-api-app-with.html
* http://sergiodelamo.es/how-to-secure-your-grails-3-api-with-spring-security-rest-for-grails/
* https://asoftwareguy.com/2014/03/17/using-grails-rest-for-authentication-in-an-angularjs-spa/
* http://hantsy.blogspot.com.es/2014/10/the-final-mile-upgrade-to-grails-243.html
* http://www.oodlestechnologies.com/blogs/Spring-Security-Rest-configuration-to-create-anonymous-accessible-URI's
* http://www.ibm.com/developerworks/library/mo-build-a-hybrid-mobile-app-ionic-grails-bluemix-trs/index.html

**Comment by alvarosanchez** [comment]
Sample projects found:

* https://github.com/dmahapatro/grails-spring-security-rest-sample

**Comment by alvarosanchez** [comment]
Articles linked. The tutorial will go into a Grails Guide: http://guides.grails.org/
