### ISSUE TITLE
Token validation only possible ?

### ISSUE THREAD

**Issue by xmlking** [alvarosanchez/grails-spring-security-rest#300]
I am building three  apps with grails 3 +  spring-security-rest 2 plugin 
1. Auth Server - responsible for issuing JWT backed by its own DB or LDAP
2. API Server - this is exposing some REST API  backed by different database.
3. SPA App - web server hosting Angular WebApp.
My requirement is: SPA app login at 1. Auth Server and get JWT, then send  the JWT to 2. API Server to access some REST resource. 

Can I use **spring-security-rest**  plugin with  API Server for just validating JWT issued by 1. Auth Server? 
Is there a way to disable */api/login* uri for API Server?
Can API Server programmatically access , username that was send in JWT?

Thanks

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

You can also try with asking in the [`#spring-security-rest` channel in Slack](https://grails.slack.com/messages/spring-security-rest).

That being said, to answer your questions:

> Can I use spring-security-rest plugin with API Server for just validating JWT issued by 1. Auth Server? 

Yes.

> Is there a way to disable /api/login uri for API Server?

Set `grails.plugin.springsecurity.rest.login.active` to `false`. It is documented: http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/index.html#_authentication_endpoint

> Can API Server programmatically access , username that was send in JWT?

http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/index.html#_token_validation_filter
