### ISSUE TITLE
plugin returns token on login for dev but no token for production

### ISSUE THREAD

**Issue by norricorp** [alvarosanchez/grails-spring-security-rest#305]
So angular code for logging in
vm.login = function () {
        $http.post('/api/login', {
            username: vm.user.username,
            password: vm.user.password
        }).then(function (response) {
            console.log("NORRIS: password good");
            vm.authenticated = true;
            console.log("NORRIS: access token is " + response.data.access_token);
            $window.sessionStorage.token = response.data.access_token;
            vm.todos = Todo.list();
        });

When I run this via grail run-app for development, I enter user/password and I get

```
POST http://centos64:8080/api/login  200 OK
NORRIS: password good
NORRIS: access token is eyJhbGciOiJIUzI1NiJ9. (etc etc)
GET http://centos64:8080/api/todos  200 OK
```

and then a listing of the todos. All is well.

When I create a war file, import that into tomcat on a different machine, enter user / password with result of
POST http://centos7-ansible:8080/api/login   302 Found
GET http://centos7-ansible:8080/api/login/auth 200 OK
NORRIS: password good
NORRIS: access token is undefined
GET http://centos7-ansible:8080/api/api/todos  401 Unauthorized
"NetworkError: 401 Unauthorized - http://centos7-ansible:8080/api/api/todos"

So the token is undefined.
Any ideas why this would be happening? What have I done wrong?

**Comment by alvarosanchez** [comment]
As it was mentioned to you in Slack, your war was incorrectly generated. Closing this.
