### ISSUE TITLE
How to handle deserialization issue when working with different version of grails-spring-security-rest 

### ISSUE THREAD

**Issue by ankittater** [alvarosanchez/grails-spring-security-rest#311]
Hi,I am are facing issue while using two grails server with different spring security version , token store by one server can not be used in another server, because spring security have  upgraded serialVersionUID from 320 to 410.
 I am running one server with grails 2.4.2 and other with grails 3.4.2, how can i handle this without upgrading grails project, and also i can not use  latest version of this plugin in grails 2.X project as it will we incompatible.
What are the possible ways to handle this situation?

Here is the error:
Message: org.springframework.security.core.userdetails.User; local class incompatible: stream classdesc serialVersionUID = 410, local class serialVersionUID = 320

**Comment by ankittater** [comment]
Solution I used is to change the serialVersionUID in Spring Security Core's source file

**Comment by lorenzoGP** [comment]
Hi @ankittater we are having the same issue. Can you tell me where did you change serialVersionUID, I can't find a way to access the  Spring Security Core's source file.

**Comment by ankittater** [comment]
Hi, You need to modify Spring Security Core  Plugin and then you need to use modified one in spring security rest plugin.

**Comment by sdelamo** [comment]
@ankittater can you point me to the code you changed in Spring Security Core Plugin. I can try to support that in Spring Security Core.

**Comment by ankittater** [comment]
You need to change in following file,
https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/SpringSecurityCoreVersion.java

replace 500L based on your need.
public static final long SERIAL_VERSION_UID = 500L;
