### ISSUE TITLE
Remove compile dependency on iText if possible

### ISSUE THREAD

**Issue by scrain** [alvarosanchez/grails-spring-security-rest#314]
The iText library has changed its licensing over its history and can cause some concerns in enterprises during OSS licensing scan/reviews.  I think the somewhat older version being used here in the project is probably ok, but it would be simpler if it could just be removed completely.  I cloned the repo and confirmed it builds and all tests pass with the dependency removed.

https://github.com/alvarosanchez/grails-spring-security-rest/blob/53f4d4e1f82f2fb5c9cd070f7fe736be2dd80200/spring-security-rest/build.gradle#L29

**Comment by alvarosanchez** [comment]
Fixed via 9e2d842173b0258be483254f32118ab21d6e5a87
