### ISSUE TITLE
Allow JSON posting to RestOauthController#accessToken

### ISSUE THREAD

**Issue by painfulcranium** [alvarosanchez/grails-spring-security-rest#316]
Any thoughts on whether or not to include an additional method and command object and expose the /oauth/access_token endpoint as a REST API endpoint? I needed to do this for an app I am working on and extended the controller into my own app, but if this is something that might be useful for others can it be added to the main RestOauthController as a second accessToken method signature?

**Comment by patrikeev** [comment]
+1

**Comment by alvarosanchez** [comment]
That goes against https://tools.ietf.org/html/rfc6749#section-6

**Comment by painfulcranium** [comment]
Thanks for looking at this....I should have updated to close this out as the only thing I ended up really looking to do was to perform a POST to the login endpoint with user/pass over https to get a JWT in response, not refresh a token.

**Comment by alvarosanchez** [comment]
Understood, thanks.

That has been always possible with the `/api/login` endpoint.
