### ISSUE TITLE
RestAuthenticationProvider does not check if a user is disabled? (Security risk?!)

### ISSUE THREAD

**Issue by tkvw** [alvarosanchez/grails-spring-security-rest#317]
Using version 2.0.0M2.
Hello, first of all I am not a security expert and maybe I am missing something, but JwtTokenStorageService deserializes a UserDetails from the GWT token which never expires and is always enabled. Isn't this a security risk? I understand the protocol is stateless, but querying userDetailService for a UserDetails seems a good idea to me, or am I missing something? 
Now, once a user is granted a token it can access rest resources regardless if the user changes it's password, the user is disabled or even worse, if the user is removed. 
Am I missing a security filter or is this really an issue?

**Comment by tkvw** [comment]
@See: pull request #319 for a possible solution

**Comment by alvarosanchez** [comment]
> JwtTokenStorageService deserializes a UserDetails from the GWT token which never expires and is always enabled

This is not true. JWT tokens always expire by default (1 hour).

> Now, once a user is granted a token it can access rest resources regardless if the user changes it's password, the user is disabled or even worse, if the user is removed.

This is the normal behaviour in all security frameworks. For example in Spring Security Core, user's roles, password, enabled, etc is only checked at login time. Once the user has authenticated, the principal will be stored in the HTTP Session and no further checks will be performed while the session is active.

**Comment by tkvw** [comment]
Hello Alvaro, 

I agree with you, but the refresh_token does not expire and recreates the AccessToken as well. So with the refresh_token the accessToken can be recreated indefinite, without checking if the user actually exists. This can be simply fixed by checking if the deserialized principal exists in the RestOauthController. Or am I wrong again?
