### ISSUE TITLE
How to use encoded token for GormTokenStorage 

### ISSUE THREAD

**Issue by kcretheesh** [alvarosanchez/grails-spring-security-rest#324]
I am using Grails version 2.4.3, spring security core 2.0.X and spring security rest plugin 1.5.4.
I had tried to implement Gorm storage for rest token and able to store token in domain class. But now I want to store encoded value insted of token value, and then I can able to store token in encoded form by beforeInsert intercepter in tokenDomainClassName. But I can't able to validate with this encoded token value. Need any modification in spring security core authentication.?

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

You can also try with asking in the [`#spring-security-rest` channel in Slack](https://grails.slack.com/messages/spring-security-rest).
