### ISSUE TITLE
Improve error handing in RestOauthController

### ISSUE THREAD

**Issue by donalmurtagh** [alvarosanchez/grails-spring-security-rest#325]
My app is using version 1.5.4 of the plugin. When the client authenticates using (Google) OAuth, the `frontendCallbackUrl` is always provided by the client via the `callback` URL parameter. This callback URL is stored in the session when the first request is made to the Grails app, and is retrieved from the session when the Grails app redirects back to the client. 

Occasionally, the attempt to retrieve the callback URL from the session fails, we're not exactly sure why (and that's not really the point of this issue), but it's not something obvious like non-sticky sessions, because I've seen it happen when running locally.

I've added some `//` comments to the relevant code below to explain what happens when the callback URL is not found in the session
```
    def callback(String provider) {
        WebContext context = new J2EContext(request, response)
        def frontendCallbackUrl

        // Try unsuccessfully to get the URL from the session
        if (session[CALLBACK_ATTR]) {
            log.debug "Found callback URL in the HTTP session"
            frontendCallbackUrl = session[CALLBACK_ATTR]
        } else {
            log.debug "Found callback URL in the configuration file"

            // Try to get the URL from the config instead, there is no such config key, but when you
            // attempt to retrieve a non-existent config key, an instance of ConfigObject is returned.
            frontendCallbackUrl = grailsApplication.config.grails.plugin.springsecurity.rest.oauth.frontendCallbackUrl
        }

        try {
            String tokenValue = restOauthService.storeAuthentication(provider, context)
            frontendCallbackUrl = getCallbackUrl(frontendCallbackUrl, tokenValue)

        } catch (Exception e) {
            def errorParams = new StringBuilder()

            Map params = callbackErrorHandler.convert(e)
            params.each { key, value ->
                errorParams << "&${key}=${value.encodeAsURL()}"
            }

            frontendCallbackUrl = getCallbackUrl(frontendCallbackUrl, errorParams.toString())
        }

        log.debug "Redirecting to ${frontendCallbackUrl}"
        redirect url: frontendCallbackUrl
    }

    private String getCallbackUrl(baseUrl, String queryStringSuffix) {
        session[CALLBACK_ATTR] = null

        // baseUrl is of type ConfigObject, so we eventually get an exception here because
        // baseUrl + queryStringSuffix causes a MissingMethodException
        // No signature of method: groovy.util.ConfigObject.plus()
        baseUrl instanceof Closure ? baseUrl(queryStringSuffix) : baseUrl + queryStringSuffix
    }
```

There are various improvements that could be made, e.g. checking that that the `frontendCallbackUrl` is actually a valid URL once it's been retrieved from the config/session. This would at least make it a lot more obvious what the underlying problem is when this error occurs.

A specific problem with the current implementation is that when the attempt to retrieve the `frontendCallbackUrl` fails, the flow of execution never returns to the client.

One way to improve this would be extend the functionality of `CallbackErrorHandler`, e.g. by adding a method that handles a failure to retrieve the `frontendCallbackUrl`. The default implementation of this method would probably just throw an exception, but it could be overridden in an application to return a URL that will show an error page in the client app.

**Comment by alvarosanchez** [comment]
While this improvement sounds good, it's not a priority right now. Also, your request #326 would improve this area.

In any case, you can always subclass `RestOauthController` with your own, improved, error handling.
