### ISSUE TITLE
Allow storage and retrieval of frontend callback URL to be customised

### ISSUE THREAD

**Issue by donalmurtagh** [alvarosanchez/grails-spring-security-rest#326]
If the `frontendCallbackURL` is supplied via the `callback` URL parameter (rather than the Grails config.) it is stored and retrieved in the HTTP session. Storing state in the session creates a number of problems and also means the claim of "stateless" made by this plugin is not entirely accurate.

In order to avoid using the session, could the mechanism used to store the callback URL be made configurable?

- Introduce a Spring bean that implements a `FrontendUrlStorage` interface, with methods for storing and retrieving the URL
- Rework the plugin such that this Spring bean is used for callback URL storage/retrieval
- The default implementation of  `FrontendUrlStorage` used by the plugin should use the session (and Grails configuration) to preserve backwards compatibility

In my application, I'd like to pass the callback URL between the client and server via a cookie instead, so I'd simply have to replace the default implementation of `FrontendUrlStorage` with a cookie-based implementation.

Alternatively, the cookie-based implementation could be included with the plugin, and enabled via a config parameter?

@alvarosanchez if you approve of this change, let me know and I'll submit a PR. I'm currently using version 1.5.4 of the plugin, so ideally I'd like this change to be backported to 1.5.X. If this is acceptable, should I submit separate PRs for each version?

**Comment by alvarosanchez** [comment]
@donalmurtagh sorry for coming across this so late. Feel free with the PRs. This project uses gitflow.

**Comment by donalmurtagh** [comment]
@alvarosanchez TBH, I'm unlikely to submit a PR as I've "moved on" from this issue

**Comment by alvarosanchez** [comment]
I understand, and apologise for the delay. Thanks!
