### ISSUE TITLE
Exception with current Spring Boot

### ISSUE THREAD

**Issue by sreim** [alvarosanchez/grails-spring-security-rest#339]
It seems like they moved FilterRegistrationBean to org.springframework.boot.web.servlet. The current version 2.0.0.M2, using Grails 3.3.0.M2 does not support this: java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/FilterRegistrationBean

**Comment by sdelamo** [comment]
Define your spring security core dependency explicitely 

   compile 'org.grails.plugins:spring-security-core:3.2.0.M1'

**Comment by alvarosanchez** [comment]
Not necessary in the latest version of spring-security-rest.
