### ISSUE TITLE
Not getting an 401 Unauthorized on @Secure["ROLE"] requests

### ISSUE THREAD

**Issue by EmilianoCenizo** [alvarosanchez/grails-spring-security-rest#342]
Hi there!

First, thank you for your effort with the plugin; its really helping me a lot on my thesis right now.

I have a small question; probably a configuration thing.

So I have everything by default... I'm doing a REST only app (no front); but when I (on purpose) do a request unauthenticated against a controller with the @Secured(['ROLE_USER']) annotation; instead of a 401 Unauthorized; I get a 404...

This is because it tries to redirect to the /auth/login form from the Spring security core I guess?

Anyway... is there any way I could force that every unauthorized request just returns an 401? (Maybe a custom JSON?)

Thanks in advance!

**Comment by volnei** [comment]
It does not look like this is a redirect, status 401 is by default (when using rest request). It seems to be an error in the application itself.

**Comment by alvarosanchez** [comment]
You need to configure your filter chains accordingly:

http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_plugin_configuration
