### ISSUE TITLE
Custom userDetails object

### ISSUE THREAD

**Issue by panksoni** [alvarosanchez/grails-spring-security-rest#353]
I am using custom user details object calling using REST plugin. I am able to access the custom fields while generating the token. However when I access the spring security principal on subsequent calls in the controller, I only get the implementation of default UserDetails and not my custom user details object.

**Comment by volnei** [comment]
+1 Same problem here

**Comment by alvarosanchez** [comment]
Use `springSecurityService.principal`.

http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#tokenValidation
