### ISSUE TITLE
GORM, when does the token expire?

### ISSUE THREAD

**Issue by odimou** [alvarosanchez/grails-spring-security-rest#358]
Hi there,

I'm using Spring Rest Security for Grails, and I store the tokens in a sql database with dateCreated, lastUpdated, tokenValue, and username. Currently it doesn't seem that these tokens expire, do they have an expiration date? Token values looks like: "2uasgurrvl6g4rj1o3n8r3enbho0014a"

Thanks for the great work,
Orestis

**Comment by verglor** [comment]
According to [documentation](http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs):

> You’ll have to handle token expiration by yourself via Quartz jobs or a similar mechanism. There are various ways you might go about this.

See section [9.3.1. GORM Token Expiration Examples](http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_gorm_token_expiration_examples)

**Comment by alvarosanchez** [comment]
They don't expire by itself, as pointed out by @verglor.

Apart from implementing expiration yourself, you can also use Memcached or Redis, in which case they will expire automatically after the configured interval.
