### ISSUE TITLE
Move oauth authentication to separate subproject

### ISSUE THREAD

**Issue by verglor** [alvarosanchez/grails-spring-security-rest#360]
It would be useful to move oauth functionality to separate subproject (e.g. spring-security-rest-oauth).
If someone doesn't need oauth it would be much lighter.
If someone uses other oauth solution, it would prevent library and url mappings conflicts.

**Comment by alvarosanchez** [comment]
While I understand your argument, one can achieve the same by excluding the unwanted dependencies in Gradle.

As with the URL mappings, application's `UrlMappings` always take precedence over plugins'.

**Comment by alvarosanchez** [comment]
Duplicates #209
