### ISSUE TITLE
Bearer error="invalid_token" even on enough privilege

### ISSUE THREAD

**Issue by ChiranjibKarn** [alvarosanchez/grails-spring-security-rest#365]
I have an RESTful Grails 3.2.11 back-end application with spring-security-rest:2.0.0.M2 plugin. 
It works fine with angular front-end.
On login from mobile (**android**) app, it gives me token back. But using the same token as Bearer in successive secured APIs it throws 

> WWW-authenticate: Bearer error="invalid_token"

 In response header.
I have crossed checked, the logged-in user has enough privilege to visit those APIs, so it is not the case of unauthorized access.

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

You can also try with asking in the [`#spring-security-rest` channel in Slack](https://grails.slack.com/messages/spring-security-rest).
