### ISSUE TITLE
@Secured(['permitAll']) not working

### ISSUE THREAD

**Issue by volnei** [alvarosanchez/grails-spring-security-rest#366]
Is it expected to work?

**Comment by alvarosanchez** [comment]
It does work.

This controller is part of all the test apps that run on CI:

https://github.com/alvarosanchez/grails-spring-security-rest/blob/develop/spring-security-rest-testapp-profile/skeleton/grails-app/controllers/rest/AnonymousController.groovy

**Comment by sdelamo** [comment]
@volnei  Check also Anonymous access https://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/index.html#_anonymous_access

**Comment by volnei** [comment]
Thanks :)
