### ISSUE TITLE
Fully qualified domain class name required to store Token using GORM

### ISSUE THREAD

**Issue by dmahapatro** [alvarosanchez/grails-spring-security-rest#37]
Based on the documentation about [GORM Token Storage](http://alvarosanchez.github.io/grails-spring-security-rest/docs/guide/single.html#gorm), the domain class has to be mentioned as a fully qualified class instead of just the name of the class.

```
grails.plugin.springsecurity.rest.token.storage.gorm.tokenDomainClassName = 
    'AuthenticationToken'
```

The above config setting will fail to store the token because of [this implementation in `GromTokenStorageService.groovy`](https://github.com/alvarosanchez/grails-spring-security-rest/blob/release/1.3.0/src/groovy/com/odobo/grails/plugin/springsecurity/rest/token/storage/GormTokenStorageService.groovy#L41)

`grailsApplication.getClassForName(tokenClassName)` expects that the class name provided is a fully qualified name (should include package as well). In that case the config should look like (say for example package `com.example.auth` for domain class `AuthenticationToken` ):

```
grails.plugin.springsecurity.rest.token.storage.gorm.tokenDomainClassName = 
    'com.example.auth.AuthenticationToken'
```

If we want to provide the flexibility of providing only the class name and not the fully qualified package name in config then the logic in `GormTokenStorageService` has to change as below:

```
def dc = grailsApplication.domainClasses?.find { it.clazz.simpleName == tokenClassName }?.clazz
```

[here](https://github.com/alvarosanchez/grails-spring-security-rest/blob/release/1.3.0/src/groovy/com/odobo/grails/plugin/springsecurity/rest/token/storage/GormTokenStorageService.groovy#L41) and [here](https://github.com/alvarosanchez/grails-spring-security-rest/blob/release/1.3.0/src/groovy/com/odobo/grails/plugin/springsecurity/rest/token/storage/GormTokenStorageService.groovy#L69)

**Comment by Champa123** [comment]
@alvarosanchez Hello álvaro. I´m using version 1.4.0 of spring security rest plugin.
Im having some configuration issues, but may be because of not understanding completely.
Im wondering if i use memcached do i need to define a TokenDomainClass?
What is the purpose of this class if not using GORM?
