### ISSUE TITLE
How to configure custom token storage?

### ISSUE THREAD

**Issue by ShurikAg** [alvarosanchez/grails-spring-security-rest#370]
We are digging into some options of using the plugin to integrate with Auth0  and one somewhat clear way we found is by implementing a custom token storage which will validate the token against Auth0.

The one thing that I didn't find in the documentation is how to configure custom token storage?

Thanks,

**Comment by alvarosanchez** [comment]
You would need to implement the [`TokenStorageService`](http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/gapi/grails/plugin/springsecurity/rest/token/storage/TokenStorageService.html) interface and register it as a bean in the Spring context.
