### ISSUE TITLE
Slow Login Times

### ISSUE THREAD

**Issue by harjitdotsingh** [alvarosanchez/grails-spring-security-rest#371]
When I login in the first time, the application takes a long time to do that. After that the subsequent logins don't take time. I don't think there is anything in the app which is causing it. Do you know if there is anything to do with Spring Security or something which is being cached which expires after some time. Just trying to see how we can troubleshoot this. I'm on grails version 3.2.5

**Comment by alvarosanchez** [comment]
Authentication isn't handled by this plugin. You would need to profile your requests to find where the time is being spent on.

**Comment by harjitdotsingh** [comment]
I will check. Thanks
