### ISSUE TITLE
Getting an error when upgrading to 3.3.5

### ISSUE THREAD

**Issue by harjitdotsingh** [alvarosanchez/grails-spring-security-rest#372]
I just upraded to 3.3.5 and I see this error 

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplicationPostProcessor' defined in loci.authentication.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is grails.plugins.exceptions.PluginException: Failed to initialize class [grails.plugin.springsecurity.rest.RestOauthController] from plugin [springSecurityRest] : grails/artefact/AsyncController

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

You can also try with asking in the [`#spring-security-rest` channel in Slack](https://grails.slack.com/messages/spring-security-rest).
