### ISSUE TITLE
Error when spring security is disabled

### ISSUE THREAD

**Issue by jdaugherty** [alvarosanchez/grails-spring-security-rest#389]
In SpringSecurityRestGrailsPlugin.groovy, doWithSpring is designed to not register beans if Spring Security is disabled (see below), but doWithApplicationContext is missing similar logic.  This causes errors fetching the tokenGenerator bean when spring security or rest are disabled.  

```
       def conf = SpringSecurityUtils.securityConfig
        if (!conf || !conf.active) {
            return
        }

        SpringSecurityUtils.loadSecondaryConfig 'DefaultRestSecurityConfig'
        conf = SpringSecurityUtils.securityConfig

        if (!conf.rest.active) {
            return
        }
```

**Comment by Tobbe129** [comment]
This one is very important for us, is there a workaround?
