### ISSUE TITLE
Refresh token allowed as Access Token

### ISSUE THREAD

**Issue by rafollett** [alvarosanchez/grails-spring-security-rest#391]
Passing the refresh token instead of the access token when using JWT seems to be accepted. I added an "else" case to the if(expiry) check in RestAuthenticationProvider to throw an exception in this case, since this seems to be a security vulnerability (since refresh token does not expire). If my understanding of JWT is incorrect here, please let me know, but thought this would be an improvement to the otherwise great plugin.

**Comment by vishnuaggarwal23** [comment]
Hi team,
Is there any update on this. Since, what is as per my understanding too, the refresh-token should not be able to be used as an access-token and they should have an expiry associated with them.

**Comment by alvarosanchez** [comment]
Adding a custom claim sounds good to me

**Comment by 6footGeek** [comment]
@alvarosanchez Any update on this? I see you merged a fix but it never passed the build :)
