### ISSUE TITLE
Is Routing to defaultTargetUrl like in spring security core plugin is available in spring security rest plugin ?

### ISSUE THREAD

**Issue by ghost** [alvarosanchez/grails-spring-security-rest#392]

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

You can also try with asking in the [`#spring-security-rest` channel in Slack](https://grails.slack.com/messages/spring-security-rest).
