### ISSUE TITLE
403 on token refresh when using LDAP

### ISSUE THREAD

**Issue by davew945** [alvarosanchez/grails-spring-security-rest#396]
I am getting 403 when I try to refresh a token when I am using LDAP.

using:
    compile 'org.grails.plugins:spring-security-core:3.1.2'
    compile 'org.grails.plugins:spring-security-rest:2.0.0.M2'
    compile 'org.grails.plugins:spring-security-ldap:3.0.2'

grails.plugin.springsecurity.rest.RestOauthController.line.127

                def user = tokenStorageService.loadUserByToken(refreshToken)
                User principal = user ? user as User : null
the cast throws
org.codehaus.groovy.runtime.typehandling.GroovyCastException : Cannot cast object
with class 'org.springframework.security.ldap.userdetails.Person' 
to class 'org.springframework.security.core.userdetails.User'

Thank you.

**Comment by davew945** [comment]
Here's a quick hack that might fix it.
Now to figure out how to get this fix installed so I can test and update for my users.

                User principal
                if (user && user.username && user.authorities) {
                    principal = new User(user.username, '', user.authorities)
                } else {
                    principal = user ? user as User : null
                }

**Comment by dbaylerg** [comment]
I have same issue.

**Comment by dbaylerg** [comment]
I actually think this is an issue with the Grails ldap plugin.  I've opened up this issue.
https://github.com/grails-plugins/grails-spring-security-ldap/issues/22
