### ISSUE TITLE
Minor refactor to make JwtTokenStorageService more extensible

### ISSUE THREAD

**Issue by longwa** [alvarosanchez/grails-spring-security-rest#403]
We have a custom claim (for 2FA) that is made when the user authenticates and is also stored on the UserDetails object which becomes part of the claim.

However, when a refresh is requested, the tokenStorageService doesn't use the principal from the token (rightly so) but loads a new one from userDetailsService.

We override the JwtTokenStorageService to carry over the 2FA flag if it was part of the refresh token, but the JwtTokenStorageService makes that a little wonky and I end up having to parse the JWT token again.

I have a PR that just splits the implementation into two `protected` methods that can be extended more easily.

No functional changes here, just making it easier to extend without reinventing wheels.

**Comment by alvarosanchez** [comment]
Go ahead with the PR

**Comment by longwa** [comment]
I added the change to the PR for issue 391 since it would’ve conflicted. Figured that would be easier.
