### ISSUE TITLE
An Authentication object was not found in the SecurityContext

### ISSUE THREAD

**Issue by NicolasLehoux** [alvarosanchez/grails-spring-security-rest#406]
Hi, I have a project that i would like to have a rest api to authenticate and this pluggin seems to be exactly wha ti need. My project use GORM so i followed the procedure to install it and using GORM I added the dependencies in the build.graddle : 
![buildGraddle](https://user-images.githubusercontent.com/48918105/69197807-91aa8b00-0b00-11ea-987a-170e43f534fa.png)
and i made the changes for the filterChain 
![filterchain](https://user-images.githubusercontent.com/48918105/69197835-ad159600-0b00-11ea-9618-76f70bca6f43.png)
but i keep getting errors when I try to login.
![curl request](https://user-images.githubusercontent.com/48918105/69197859-c9b1ce00-0b00-11ea-8073-679ee09bbbc4.png)
![ErrorStackTrace](https://user-images.githubusercontent.com/48918105/69197865-cd455500-0b00-11ea-9d31-5b42025e08ad.png)

I was wondering if you had any idea what could cause that problem and also any way to solve that problem.

I tried to make an empty project and adding dependencies off my project chunk by chunk to see if there was any problem with that but didnt get any result. I observed in the logs that the pluggin was well initiated 
![blankProjectBuild](https://user-images.githubusercontent.com/48918105/69288259-0811c080-0bc7-11ea-9fff-873d262b8cd5.png) 
But there was no log like that in my other project.
![baseBuild](https://user-images.githubusercontent.com/48918105/69288311-2677bc00-0bc7-11ea-8b63-0a9bd62caf83.png)
Is ther something that could prevent the plugin to initiate? Thanks in advance et I really wish to be able to use that plugin.

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

You can also try with asking in the [`#spring-security-rest` channel in Slack](https://grails.slack.com/messages/spring-security-rest).
