### ISSUE TITLE
Could we use this plugin to replace the session based authentication

### ISSUE THREAD

**Issue by ntung** [alvarosanchez/grails-spring-security-rest#408]
Hi Alvaro,

We are migrating our Grails-based application to Kubernetes to allow multiple instances running simultaneously. The inherent problem is that the application will ask users to re-login if the request is served by the other pod that is not the previously same pod. We want to replace session-based authentication with token-based authentication.

I cannot find any issues relevant to our need, so then I have raised this issue which someone experienced users can share their solutions.

If you have any idea or helpful tutorials, could you please share with us?

Thank you in advance!

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](http://stackoverflow.com/questions/tagged/grails+spring-security-rest). Label your questions with both the `grails` and `spring-security-rest` tags.

As to the question itself, yes, this plugin could be used to achieve stateless authentication.

**Comment by ntung** [comment]
My question is concerning in authenticating users via the form login.
