### ISSUE TITLE
2.x branch changes need to be merged into develop

### ISSUE THREAD

**Issue by longwa** [alvarosanchez/grails-spring-security-rest#431]
There are changes in 2.x, specifically some fixes for:

https://github.com/alvarosanchez/grails-spring-security-rest/pull/402/commits

That are not present in the more current release. I believe this branch was never merged into develop branch.

Unless, we merge, several issues will be re-introduced including the ability to use a refresh token as an access token indefinitely (since they don't expire by default).

**Comment by longwa** [comment]
PR: https://github.com/alvarosanchez/grails-spring-security-rest/pull/432

**Comment by alvarosanchez** [comment]
Good catch! I've merged it and will release 3.0.1
