### ISSUE TITLE
Error creating bean with name 'tokenGenerator' - The secret length must be at least 256 bits

### ISSUE THREAD

**Issue by fco271292** [alvarosanchez/grails-spring-security-rest#489]
I use `grails 4.0.4`,  `spring-security-core:4.0.3` and `spring-security-rest:3.0.1,` at the time of the use `grails.plugin.springsecurity.rest.token.storage.jwt.secret = 'JWT_SECRET_APP' ` show the message: `Error creating bean with name 'tokenGenerator': Invocation of init method failed; nested exception is com.nimbusds.jose.KeyLengthException: The secret length must be at least 256 bits`,  can you help me, thanks in advance.

**Comment by puneetbehl** [comment]
The value of `grails.plugin.springsecurity.rest.token.storage.jwt.secret` should be atleast 256 bits (32 characters). But `JWT_SECRET_APP` is 112 bits only. I think `'MY_APPLICATION_JWT_SECRET_KEY_DUMMY'` should be okay.
