### ISSUE TITLE
Problem building project today

### ISSUE THREAD

**Issue by rkimaoui** [alvarosanchez/grails-spring-security-rest#492]
Hello,

I got this error when building my project today:

`
> Could not resolve all files for configuration ':runtime'.
   > Could not find any matches for net.minidev:json-smart:[1.3.1,2.3] as no versions of net.minidev:json-smart are available.
     Searched in the following locations:
       - https://repo.grails.org/grails/core/net/minidev/json-smart/maven-metadata.xml
       - https://repo.grails.org/grails/core/net/minidev/json-smart/
     Required by:
         project : > org.grails.plugins:spring-security-rest:3.0.0.RC1 > com.nimbusds:nimbus-jose-jwt:4.36
Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

I think it's related with this issue :  [https://github.com/grails/grails-core/issues/11825](url).
The workaround mentioned there doesn't work for grails-spring-security-rest/

**Comment by jdaugherty** [comment]
This was likely a network blip. I'm going to close this ticket, but if you continue to have it, please let me know and we can reopen.
