### ISSUE TITLE
Potentially insecure token refresh

### ISSUE THREAD

**Issue by klcium** [alvarosanchez/grails-spring-security-rest#515]
Hello,

I found that, in the "[access_token](https://github.com/grails/grails-spring-security-rest/blob/fe71b23e69645326b70e9e145b5c02a00234e4b0/spring-security-rest/grails-app/controllers/grails/plugin/springsecurity/rest/RestOauthController.groovy#L121)" function (from RestOauthController.groovy) in charge of generating a new access token when a user povides a refresh token does not check the type of the passed token before parsing its details ([loaduserbytoken](https://github.com/grails/grails-spring-security-rest/blob/fe71b23e69645326b70e9e145b5c02a00234e4b0/spring-security-rest/grails-app/controllers/grails/plugin/springsecurity/rest/RestOauthController.groovy#L132))

As a result, one may provide an access token instead of a refresh token. The user will be sent back a fresh access token. 

The security risk here is that a leaked access token (if stolen before expiration) may be renewed by an attacker to persist indefinitely in the system.

**Comment by jdaugherty** [comment]
This is fixed in 6.0.x.
