### ISSUE TITLE
Grails 6.x support

### ISSUE THREAD

**Issue by vsachinv** [alvarosanchez/grails-spring-security-rest#517]
Hi @puneetbehl ,

We are upgrading application from Grails 3.x to Grails 6.x and application has dependency on spring-security-rest? Could you please tell do we have support available for Grails 6.x?

**Comment by will-districtnerds** [comment]
I've been using 3.0.1 with Grails 6.1.x without any issues so far.

**Comment by jdaugherty** [comment]
https://github.com/grails/grails-spring-security-rest/pull/521 will bring this back to life for grails 6.1.1+.  We plan to also update this plugin for Grails 7.

**Comment by vsachinv** [comment]
@jdaugherty Thanks for your reply but We have upgraded the plugin to Grails 6.x as we needed the same in our apps. Shall I share the PR for the same?

**Comment by vsachinv** [comment]
> https://github.com/grails/grails-spring-security-rest/pull/521 will bring this back to life for grails 6.1.1+.  We plan to also update this plugin for Grails 7.

Thanks @jdaugherty that will be great.

**Comment by jdaugherty** [comment]
FYI: snapshots are now publishing to repo.grails.org for Grails 6 support - use the `5.0.0-SNAPSHOT` version to try it out.

**Comment by jdaugherty** [comment]
This is now released to central.
