### ISSUE TITLE
Provide a RedisTokenStorageService

### ISSUE THREAD

**Issue by germanSancho** [alvarosanchez/grails-spring-security-rest#88]
It would be nice having a redis implementation for the token storage service, based in the grails redis plugin

**Comment by alvarosanchez** [comment]
It was implemented at some point (few years ago), but forgot to revisit this issue.

**Comment by alvarosanchez** [comment]
https://github.com/alvarosanchez/grails-spring-security-rest/blob/develop/spring-security-rest-redis/src/main/groovy/grails/plugin/springsecurity/rest/token/storage/RedisTokenStorageService.groovy
