### ISSUE TITLE
Obtain token after form-authentication

### ISSUE THREAD

**Issue by genuinefafa** [alvarosanchez/grails-spring-security-rest#96]
Is there any way to obtain the `X-Auth-Token` after a login using standard form authentication? 

I was unable to find anything on the source code and I'm confuse if this should be a feature or not. I don't want to save the u/p to do a double login using the `/api/login` uri, it doesn't seems to be the way to go.

(This is a **question** kind of an issue, I cannot set the label myself)

**Comment by jtwoee** [comment]
TokenGenerator tokenGenerator
    String tokenValue = tokenGenerator.generateToken()
will throw out the exception? will you be able to let me know what classes you imported?
